// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATPPRResource.cpp
// Header definition of CATPPRResource
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CATPPRResource.h"
#include "CATInit.h"
#include "CATISPPProcessContainer.h"
 
CATImplementClass( CATPPRResource,
                   Implementation, 
                   CATPPRDocument,
                   CATNull );
 
//-----------------------------------------------------------------------------
// CATPPRResource : constructor
//-----------------------------------------------------------------------------
CATPPRResource::CATPPRResource():
    CATPPRDocument()
{
}

//-----------------------------------------------------------------------------
// CATPPRResource : destructor
//-----------------------------------------------------------------------------
CATPPRResource::~CATPPRResource()
{
}
 
//-----------------------------------------------------------------------------
// CATPPRResource : copy constructor
//-----------------------------------------------------------------------------
CATPPRResource::CATPPRResource(CATPPRResource& original):
   CATPPRDocument(original)
{
}
 
//-----------------------------------------------------------------------------
// CATPPRResource : equal operator
//-----------------------------------------------------------------------------
CATPPRResource& CATPPRResource::operator=(CATPPRResource& original)
{
   CATPPRDocument::operator=(original);
   return *this;
}

CATListValCATBaseUnknown_var *CATPPRResource::GetPPRRootPointer(CATDocument *pProcessDoc)
{
	if (pProcessDoc == NULL)
	{
		return NULL;
	}

	HRESULT rc = E_FAIL;
	CATInit *piInitOnDoc = NULL;
	rc = pProcessDoc -> QueryInterface(IID_CATInit,(void**)&piInitOnDoc);
	if (FAILED(rc)) return NULL;
	CATISPPProcessContainer *piProcessCont = (CATISPPProcessContainer*)piInitOnDoc -> GetRootContainer("CATISPPProcessContainer");
	if ( NULL == piProcessCont) return NULL;
	piInitOnDoc -> Release();
	piInitOnDoc = NULL;

	CATListValCATBaseUnknown_var *pResourceList = piProcessCont->GetResourceContext();
	piProcessCont -> Release();
	piProcessCont = NULL;
	if ((NULL == pResourceList) || ((*pResourceList).Size() < 1))
	{ 
		if ((*pResourceList).Size() > 0) delete pResourceList;
		return NULL;
	}

	return pResourceList;
}
