# COPYRIGHT Dassault Systemes 2016
#======================================================================
# Imakefile for module DisAssemblyUIMdl.m
#======================================================================
#
#  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP WSPROCESS ProcessPlatformVisuUUID  \
DI0PANV2 CATMathematics CATDialogEngine  \
CATApplicationFrame 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATApplicationFrame \
								   CATObjectModelerBase \
								   CATProductStructure1 \
								   CATObjectSpecsModeler \
								   CATMecModInterfaces \
								   CATDialogEngine \
								   ObjectBaseMdl \
								   PPRManagerMdl \
								   VBAScriptMdl \
								   FileManagerMdl \
								   ktTreeCtrlModule \
								   ktTreeNodeImplement \
								   CATVisualization \
								   CATxPDMInterfaces \
								   InfItfCPP \
								   InfProIDL \
								   InfPubIDL \
								   CATIAApplicationFrame \
								   CATPrint \
								   ProcessNotesMdl \
								   CATProcessInterfaces \
								   ProcessModelMdl \


# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
