// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// CDlgModelProperties.cpp
// The dialog : CDlgModelProperties
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CDlgModelProperties.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef CDlgModelProperties_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CDlgModelProperties::CDlgModelProperties() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"CDlgModelProperties",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame001 = NULL;
 _CheckButton002 = NULL;
 _Combo003 = NULL;
 _CheckButton004 = NULL;
 _Combo005 = NULL;
 _Combo006 = NULL;
 _CheckButton007 = NULL;
 _CheckButton008 = NULL;
 _Combo009 = NULL;
 _CheckButton010 = NULL;
 _Combo012 = NULL;
 _CheckButton013 = NULL;
 _Combo014 = NULL;
 _CheckButton015 = NULL;
 _Combo016 = NULL;
 _CheckButton017 = NULL;
 _Combo018 = NULL;
 _Combo020 = NULL;
 _CheckButton021 = NULL;
 _CheckButton022 = NULL;
 _Combo023 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CDlgModelProperties::~CDlgModelProperties()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame001 = NULL;
 _CheckButton002 = NULL;
 _Combo003 = NULL;
 _CheckButton004 = NULL;
 _Combo005 = NULL;
 _Combo006 = NULL;
 _CheckButton007 = NULL;
 _CheckButton008 = NULL;
 _Combo009 = NULL;
 _CheckButton010 = NULL;
 _Combo012 = NULL;
 _CheckButton013 = NULL;
 _Combo014 = NULL;
 _CheckButton015 = NULL;
 _Combo016 = NULL;
 _CheckButton017 = NULL;
 _Combo018 = NULL;
 _Combo020 = NULL;
 _CheckButton021 = NULL;
 _CheckButton022 = NULL;
 _Combo023 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void CDlgModelProperties::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridColumnResizable(0,1);
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 10, CATGRID_4SIDES);
 _CheckButton002 = new CATDlgCheckButton(this, "CheckButton002");
_CheckButton002 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Combo003 = new CATDlgCombo(this, "Combo003", CATDlgCmbDropDown);
_Combo003 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _CheckButton004 = new CATDlgCheckButton(this, "CheckButton004");
_CheckButton004 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Combo005 = new CATDlgCombo(this, "Combo005", CATDlgCmbDropDown);
_Combo005 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _Combo006 = new CATDlgCombo(this, "Combo006", CATDlgCmbDropDown);
_Combo006 -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
 _CheckButton007 = new CATDlgCheckButton(this, "CheckButton007");
_CheckButton007 -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _CheckButton008 = new CATDlgCheckButton(this, "CheckButton008");
_CheckButton008 -> SetGridConstraints(3, 1, 1, 1, CATGRID_4SIDES);
 _Combo009 = new CATDlgCombo(this, "Combo009", CATDlgCmbDropDown);
_Combo009 -> SetGridConstraints(3, 2, 1, 1, CATGRID_4SIDES);
 _CheckButton010 = new CATDlgCheckButton(this, "CheckButton010");
_CheckButton010 -> SetGridConstraints(6, 1, 1, 1, CATGRID_4SIDES);
 _Combo012 = new CATDlgCombo(this, "Combo012", CATDlgCmbDropDown);
_Combo012 -> SetGridConstraints(6, 2, 1, 1, CATGRID_4SIDES);
 _CheckButton013 = new CATDlgCheckButton(this, "CheckButton013");
_CheckButton013 -> SetGridConstraints(7, 1, 1, 1, CATGRID_4SIDES);
 _Combo014 = new CATDlgCombo(this, "Combo014", CATDlgCmbDropDown);
_Combo014 -> SetGridConstraints(7, 2, 1, 1, CATGRID_4SIDES);
 _CheckButton015 = new CATDlgCheckButton(this, "CheckButton015");
_CheckButton015 -> SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
 _Combo016 = new CATDlgCombo(this, "Combo016", CATDlgCmbDropDown);
_Combo016 -> SetGridConstraints(4, 2, 1, 1, CATGRID_4SIDES);
 _CheckButton017 = new CATDlgCheckButton(this, "CheckButton017");
_CheckButton017 -> SetGridConstraints(5, 1, 1, 1, CATGRID_4SIDES);
 _Combo018 = new CATDlgCombo(this, "Combo018", CATDlgCmbDropDown);
_Combo018 -> SetGridConstraints(5, 2, 1, 1, CATGRID_4SIDES);
 _Combo020 = new CATDlgCombo(this, "Combo020", CATDlgCmbDropDown);
_Combo020 -> SetGridConstraints(9, 2, 1, 1, CATGRID_4SIDES);
 _CheckButton021 = new CATDlgCheckButton(this, "CheckButton021");
_CheckButton021 -> SetGridConstraints(9, 1, 1, 1, CATGRID_4SIDES);
 _CheckButton022 = new CATDlgCheckButton(this, "CheckButton022");
_CheckButton022 -> SetGridConstraints(8, 1, 1, 1, CATGRID_4SIDES);
 _Combo023 = new CATDlgCombo(this, "Combo023", CATDlgCmbDropDown);
_Combo023 -> SetGridConstraints(8, 2, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION
CATDlgWindow *pFrmWindow = NULL;
pFrmWindow = (CATApplicationFrame::GetApplicationFrame())->GetApplicationDocument();
DRECT rect;
pFrmWindow->GetRectDimensions(&rect);
int width = 600;
int height = 400;
this->SetRectDimensions((rect.dx-width)/2,(rect.dy-height)/2,height,width);
//_Frame001->SetGridRowResizable(0,1);
//_Frame001->SetGridColumnResizable(0,1);
//pTreeCtrl = new CAATreeCtrl(_Frame001,"TreeCtrl");
//pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
//pTreeCtrl->AddRootTreeNode("","");
//生成BOM树
GenerateBOMTree(_Frame001);
_Combo003->SetLine("一级",0);
_Combo003->SetLine("二级",1);
_Combo003->SetLine("三级",2);
_Combo003->SetLine("四级",3);
_Combo003->SetLine("五级",4);
_Combo003->SetLine("六级",5);
_Combo003->SetLine("七级",6);
_Combo003->SetLine("八级",7);
_Combo003->SetLine("九级",8);

_Combo005->SetLine("一级",0);
_Combo005->SetLine("二级",1);
_Combo005->SetLine("三级",2);
_Combo005->SetLine("四级",3);
_Combo005->SetLine("五级",4);
_Combo005->SetLine("六级",5);
_Combo005->SetLine("七级",6);
_Combo005->SetLine("八级",7);
_Combo005->SetLine("九级",8);

_Combo006->SetLine("一级",0);
_Combo006->SetLine("二级",1);
_Combo006->SetLine("三级",2);
_Combo006->SetLine("四级",3);
_Combo006->SetLine("五级",4);
_Combo006->SetLine("六级",5);
_Combo006->SetLine("七级",6);
_Combo006->SetLine("八级",7);
_Combo006->SetLine("九级",8);

_Combo009->SetLine("一级",0);
_Combo009->SetLine("二级",1);
_Combo009->SetLine("三级",2);
_Combo009->SetLine("四级",3);
_Combo009->SetLine("五级",4);
_Combo009->SetLine("六级",5);
_Combo009->SetLine("七级",6);
_Combo009->SetLine("八级",7);
_Combo009->SetLine("九级",8);
//CAA2 WIZARD CALLBACK DECLARATION SECTION
     AddAnalyseNotificationCB (this, 
                               GetDiaCANCELNotification(),
                               (CATCommandMethod)&CDlgModelProperties::OnCDlgModelPropertiesDiaCANCELNotification,
                               NULL);
     AddAnalyseNotificationCB (this, 
                               GetDiaOKNotification(),
                               (CATCommandMethod)&CDlgModelProperties::OnCDlgModelPropertiesDiaOKNotification,
                               NULL);
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}


//-------------------------------------------------------------------------
// Callback on DiaOK of _CDlgModelProperties
//-------------------------------------------------------------------------
void CDlgModelProperties::OnCDlgModelPropertiesDiaOKNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
}


//-------------------------------------------------------------------------
// Callback on DiaCANCEL of _CDlgModelProperties
//-------------------------------------------------------------------------
void CDlgModelProperties::OnCDlgModelPropertiesDiaCANCELNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
}


CATBoolean CDlgModelProperties::GenerateBOMTree(CATDlgFrame* frame)
{
	frame->SetGridRowResizable(0,1);
	frame->SetGridColumnResizable(0,1);
	pTreeCtrl = new CAATreeCtrl(frame,"TreeCtrl");
	pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
	pTreeCtrl->AddRootTreeNode("ZP_ASM","");
	CATBaseUnknown *pTreeNode = NULL;
	CATBaseUnknown* pFatherNode = NULL;
	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-ZP-DWPZJ_ASM","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-1XZ","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-2DWP","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-4DP","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-3LD","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-3LD2","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-ZP-ZCZJ1","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-1LJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-2DCDWB1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-3DCDWB2","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-4ZEDWB1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-5ZEDWB2","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-6GXYB1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-7GXYB2","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-9DQ","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"B6X10_JB-T8013_1B-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-8XD","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T6170_M8","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X35_JB-T8015-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T6170_M8_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"B6X10_JB-T8013_1B-1999_1_11","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X35_JB-T8015-1999-11","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"2JXDWX_1-1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	return TRUE;
}
