// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// CDlgFuzzyModel.cpp
// The dialog : CDlgFuzzyModel
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CDlgFuzzyModel.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef CDlgFuzzyModel_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CDlgFuzzyModel::CDlgFuzzyModel() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"CDlgFuzzyModel",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame001 = NULL;
 _Frame002 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CDlgFuzzyModel::~CDlgFuzzyModel()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame001 = NULL;
 _Frame002 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void CDlgFuzzyModel::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridRowResizable(0,1);
 SetGridColumnResizable(0,1);
 SetGridColumnResizable(1,1);
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame002 = new CATDlgFrame(this, "Frame002", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame002 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION
CATDlgWindow *pFrmWindow = NULL;
pFrmWindow = (CATApplicationFrame::GetApplicationFrame())->GetApplicationDocument();
DRECT rect;
pFrmWindow->GetRectDimensions(&rect);
int width = 600;
int height = 400;
this->SetRectDimensions((rect.dx-width)/2,(rect.dy-height)/2,height,width);
//_Frame001->SetGridRowResizable(0,1);
//_Frame001->SetGridColumnResizable(0,1);
//pTreeCtrl = new CAATreeCtrl(_Frame001,"TreeCtrl");
//pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
//pTreeCtrl->AddRootTreeNode("","");
//
//_Frame002->SetGridRowResizable(0,1);
//_Frame002->SetGridColumnResizable(0,1);
//pTreeCtrl = new CAATreeCtrl(_Frame002,"TreeCtrl");
//pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
//pTreeCtrl->AddRootTreeNode("","");

//生成BOM树
GenerateBOMTree(_Frame001);
GenerateDisBOMTree(_Frame002);
//CAA2 WIZARD CALLBACK DECLARATION SECTION
     AddAnalyseNotificationCB (this, 
                               GetDiaCANCELNotification(),
                               (CATCommandMethod)&CDlgFuzzyModel::OnCDlgFuzzyModelDiaCANCELNotification,
                               NULL);
     AddAnalyseNotificationCB (this, 
                               GetDiaOKNotification(),
                               (CATCommandMethod)&CDlgFuzzyModel::OnCDlgFuzzyModelDiaOKNotification,
                               NULL);
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}


//-------------------------------------------------------------------------
// Callback on DiaOK of _CDlgFuzzyModel
//-------------------------------------------------------------------------
void CDlgFuzzyModel::OnCDlgFuzzyModelDiaOKNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
}


//-------------------------------------------------------------------------
// Callback on DiaCANCEL of _CDlgFuzzyModel
//-------------------------------------------------------------------------
void CDlgFuzzyModel::OnCDlgFuzzyModelDiaCANCELNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
}


CATBoolean CDlgFuzzyModel::GenerateBOMTree(CATDlgFrame* frame)
{
	frame->SetGridRowResizable(0,1);
	frame->SetGridColumnResizable(0,1);
	pTreeCtrl = new CAATreeCtrl(frame,"TreeCtrl");
	pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
	pTreeCtrl->AddRootTreeNode("ZP_ASM","");
	CATBaseUnknown *pTreeNode = NULL;
	CATBaseUnknown* pFatherNode = NULL;
	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-ZP-DWPZJ_ASM","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-1XZ:0.97","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-2DWP:0.85","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-4DP:0.91","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-3LD:0.96","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"1-3LD2:0.81","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-ZP-ZCZJ1:0.41","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-1LJB:0.89","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-2DCDWB1:0.99","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-3DCDWB2:0.65","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-4ZEDWB1:0.78","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-5ZEDWB2:0.95","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-6GXYB1:0.79","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-7GXYB2:0.99","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-9DQ:0.05","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"B6X10_JB-T8013_1B-1999:0.99","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"4-8XD","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T6170_M8","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X35_JB-T8015-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T6170_M8_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"B6X10_JB-T8013_1B-1999_1_11","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X35_JB-T8015-1999-11","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"2JXDWX_1-1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	return TRUE;
}

CATBoolean CDlgFuzzyModel::GenerateDisBOMTree(CATDlgFrame* frame)
{
	frame->SetGridRowResizable(0,1);
	frame->SetGridColumnResizable(0,1);
	pTreeCtrl = new CAATreeCtrl(frame,"TreeCtrl");
	pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
	pTreeCtrl->AddRootTreeNode("拆卸前端防热环","");
	CATBaseUnknown *pTreeNode = NULL;
	CATBaseUnknown* pFatherNode = NULL;
	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸垂挂吊索","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸前端整流罩","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸中隔板设备电连接器","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸小舱内电缆1","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸监控设备","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸雷达电力设备","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸调频设备","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸小舱内电缆2","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸基准设备","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸基准设备电缆","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸天线控制器","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸小舱内电缆3","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸驱动设备","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸固定螺栓组1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"断开电路板主线路","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸热敏传感器","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸固定螺栓组2","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"拆卸","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T6170_M8：0.94","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X35_JB-T8015-1999：0.99","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000：0.99","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T6170_M8_1_1：0.99","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"B6X10_JB-T8013_1B-1999_1_11：0.98","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X35_JB-T8015-1999-11：0.98","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"2JXDWX_1-1：0.91","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-ZP-ZCZJ2","");

	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-1GDZJLJB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"6-2GDZJDWB","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"AM8X16XL_JB-T8007_3-1999","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"GB-T5783_M8X25","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"5X20_GB-T119_2-2000_1_1","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"A8X20_JB-T8015-1999_1","");

	return TRUE;
}

