// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// CDlgNewDisAssembly.cpp
// The dialog : CDlgNewDisAssembly
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CDlgNewDisAssembly.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef CDlgNewDisAssembly_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CDlgNewDisAssembly::CDlgNewDisAssembly() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"CDlgNewDisAssembly",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Label002 = NULL;
 _Editor003 = NULL;
 _Label004 = NULL;
 _Editor005 = NULL;
 _PushButton006 = NULL;
 _PushButton007 = NULL;
 _Frame009 = NULL;
 _Frame010 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CDlgNewDisAssembly::~CDlgNewDisAssembly()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Label002 = NULL;
 _Editor003 = NULL;
 _Label004 = NULL;
 _Editor005 = NULL;
 _PushButton006 = NULL;
 _PushButton007 = NULL;
 _Frame009 = NULL;
 _Frame010 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void CDlgNewDisAssembly::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridRowResizable(2,1);
 SetGridColumnResizable(0,1);
 _Label002 = new CATDlgLabel(this, "Label002");
_Label002 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Editor003 = new CATDlgEditor(this, "Editor003");
_Editor003 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Label004 = new CATDlgLabel(this, "Label004");
_Label004 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Editor005 = new CATDlgEditor(this, "Editor005");
_Editor005 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _PushButton006 = new CATDlgPushButton(this, "PushButton006");
_PushButton006 -> SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);
 _PushButton007 = new CATDlgPushButton(this, "PushButton007");
_PushButton007 -> SetGridConstraints(1, 3, 1, 1, CATGRID_4SIDES);
 _Frame009 = new CATDlgFrame(this, "Frame009", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame009 -> SetGridConstraints(0, 0, 1, 3, CATGRID_4SIDES);
 _Frame010 = new CATDlgFrame(this, "Frame010", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame010 -> SetGridConstraints(2, 1, 3, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION
CATDlgWindow *pFrmWindow = NULL;
pFrmWindow = (CATApplicationFrame::GetApplicationFrame())->GetApplicationDocument();
DRECT rect;
pFrmWindow->GetRectDimensions(&rect);
int width = 600;
int height = 400;
this->SetRectDimensions((rect.dx-width)/2,(rect.dy-height)/2,height,width);
//_Frame009->SetGridRowResizable(0,1);
//_Frame009->SetGridColumnResizable(0,1);
//pTreeCtrl = new CAATreeCtrl(_Frame009,"TreeCtrl");
//pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
//pTreeCtrl->AddRootTreeNode("","");

//生成BOM树
GenerateBOMTree(_Frame009);
GenerateRBOMTree(_Frame010);

//_Frame010->SetGridRowResizable(0,1);
//_Frame010->SetGridColumnResizable(0,1);
//pTreeCtrl = new CAATreeCtrl(_Frame010,"TreeCtrl");
//pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
//pTreeCtrl->AddRootTreeNode("","");

CATBaseUnknown *pTreeNode = NULL;
//CAA2 WIZARD CALLBACK DECLARATION SECTION
     AddAnalyseNotificationCB (this, 
                               GetDiaCANCELNotification(),
                               (CATCommandMethod)&CDlgNewDisAssembly::OnCDlgNewDisAssemblyDiaCANCELNotification,
                               NULL);
     AddAnalyseNotificationCB (this, 
                               GetDiaOKNotification(),
                               (CATCommandMethod)&CDlgNewDisAssembly::OnCDlgNewDisAssemblyDiaOKNotification,
                               NULL);
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}


//-------------------------------------------------------------------------
// Callback on DiaOK of _CDlgNewDisAssembly
//-------------------------------------------------------------------------
void CDlgNewDisAssembly::OnCDlgNewDisAssemblyDiaOKNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
}


//-------------------------------------------------------------------------
// Callback on DiaCANCEL of _CDlgNewDisAssembly
//-------------------------------------------------------------------------
void CDlgNewDisAssembly::OnCDlgNewDisAssemblyDiaCANCELNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
}


CATBoolean CDlgNewDisAssembly::GenerateBOMTree(CATDlgFrame* frame)
{
	frame->SetGridRowResizable(0,1);
	frame->SetGridColumnResizable(0,1);
	pTreeCtrl = new CAATreeCtrl(frame,"TreeCtrl");
	pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
	pTreeCtrl->AddRootTreeNode("XXX载荷舱小舱内产品（仪器电缆）总装","");
	CATBaseUnknown *pTreeNode = NULL;
	CATBaseUnknown* pFatherNode = NULL;
	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"不带辅助工装按流程批量安装产品（设备、电缆）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱中隔板设备并电缆整理及插接","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱长隔板设备并电缆整理及插接","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱底板设备并电缆整理及插接","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"分析各安装过程总装可实施性及相关危险点、风险点","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"带辅助工装按流程批量安装产品（设备、电缆）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱内辅助工装","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱中隔板设备并电缆整理及插接","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱长隔板设备并电缆整理及插接","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱底板设备并电缆整理及插接","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（不带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱内辅助工装","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱中隔板设备并电缆整理及插接","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱长隔板设备并电缆整理及插接","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱底板设备并电缆整理及插接","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（不带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（不带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（带高辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（带低辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（不带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（带高辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（带低辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	return TRUE;
}

CATBoolean CDlgNewDisAssembly::GenerateRBOMTree(CATDlgFrame* frame)
{
	frame->SetGridRowResizable(0,1);
	frame->SetGridColumnResizable(0,1);
	pTreeCtrl = new CAATreeCtrl(frame,"TreeCtrl");
	pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
	pTreeCtrl->AddRootTreeNode("XXX载荷舱小舱内产品（仪器电缆）总装","");
	CATBaseUnknown *pTreeNode = NULL;
	CATBaseUnknown* pFatherNode = NULL;
	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（带低辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"不带辅助工装按流程批量安装产品（设备、电缆）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（带高辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（带低辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（不带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（不带辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（带高辅助工装）","");
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-中隔板产品拆装（不带辅助工装）","");
	
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱底板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱长隔板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱中隔板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱内辅助工装","");
	
	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"带辅助工装按流程批量安装产品（设备、电缆）","");
	
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱底板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱长隔板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱中隔板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱内辅助工装","");

	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"小舱复杂工况产品拆装-长隔板产品拆装（不带辅助工装）","");
	
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"分析各安装过程总装可实施性及相关危险点、风险点","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱底板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱长隔板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"安装小舱中隔板设备并电缆整理及插接","");
	
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeNode = pFatherNode;
	pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,"铺设小舱内电缆","");

	return TRUE;
}
