// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// NewDisAssemblyCmd.cpp
// The state chart based command: NewDisAssemblyCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "NewDisAssemblyCmd.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( NewDisAssemblyCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
NewDisAssemblyCmd::NewDisAssemblyCmd() :
  CATStateCommand ("NewDisAssemblyCmd", CATDlgEngOneShot, CATCommandModeExclusive) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, pOkBut(NULL), pCancelBut(NULL), pCloseBut(NULL)
{
	pDlgNewDisAssembly = new CDlgNewDisAssembly();
	pDlgNewDisAssembly->Build();
	pDlgNewDisAssembly->SetVisibility(CATDlgShow);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
NewDisAssemblyCmd::~NewDisAssemblyCmd()
{
	if (pOkBut != NULL)
	{
		pOkBut->RequestDelayedDestruction();
		pOkBut = NULL;
	}
	if (pCancelBut != NULL)
	{
		pCancelBut->RequestDelayedDestruction();
		pCancelBut = NULL;
	}
	if (pCloseBut != NULL)
	{
		pCloseBut->RequestDelayedDestruction();
		pCloseBut = NULL;
	}
	if (pDlgNewDisAssembly != NULL) 
	{
		pDlgNewDisAssembly->RequestDelayedDestruction();
		pDlgNewDisAssembly = NULL;
	}
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void NewDisAssemblyCmd::BuildGraph()
{

	pOkBut = new CATDialogAgent("OK");
	pCloseBut = new CATDialogAgent("Close");
	pCancelBut = new CATDialogAgent("Cancel");

	pOkBut->AcceptOnNotify(pDlgNewDisAssembly,pDlgNewDisAssembly->GetDiaOKNotification());
	pCancelBut->AcceptOnNotify(pDlgNewDisAssembly,pDlgNewDisAssembly->GetWindCloseNotification());
	pCloseBut->AcceptOnNotify(pDlgNewDisAssembly,pDlgNewDisAssembly->GetDiaCANCELNotification());

	CATDialogState* pState = GetInitialState("OK");
	pState->AddDialogAgent(pOkBut);
	pState->AddDialogAgent(pCloseBut);
	pState->AddDialogAgent(pCancelBut);

	AddTransition(pState,NULL,IsOutputSetCondition(pOkBut),Action((ActionMethod)&NewDisAssemblyCmd::ActionOK));
	AddTransition(pState,NULL,IsOutputSetCondition(pCloseBut),Action((ActionMethod)&NewDisAssemblyCmd::ActionClose));
	AddTransition(pState,NULL,IsOutputSetCondition(pCancelBut),Action((ActionMethod)&NewDisAssemblyCmd::ActionCancel));
  // TODO: Define the StateChart 
  // ---------------------------
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean NewDisAssemblyCmd::ActionOne( void *data )
{
  // TODO: Define the action associated with the transition 
  // ------------------------------------------------------

  return TRUE;
}

CATBoolean NewDisAssemblyCmd::ActionOK( void *data )
{
	// TODO: Define the action associated with the transition 
	// ------------------------------------------------------
	if (pDlgNewDisAssembly)
	{
		pDlgNewDisAssembly->RequestDelayedDestruction();
		pDlgNewDisAssembly = NULL;
	}
	return TRUE;
}

CATBoolean NewDisAssemblyCmd::ActionCancel( void *data )
{
	// TODO: Define the action associated with the transition 
	// ------------------------------------------------------
	if (pDlgNewDisAssembly)
	{
		pDlgNewDisAssembly->RequestDelayedDestruction();
		pDlgNewDisAssembly = NULL;
	}

	return TRUE;
}

CATBoolean NewDisAssemblyCmd::ActionClose( void *data )
{
	// TODO: Define the action associated with the transition 
	// ------------------------------------------------------
	if (pDlgNewDisAssembly)
	{
		pDlgNewDisAssembly->RequestDelayedDestruction();
		pDlgNewDisAssembly = NULL;
	}

	return TRUE;
}
