// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// HidePathCmd.cpp
// The state chart based command: HidePathCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Nov 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "HidePathCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( HidePathCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
HidePathCmd::HidePathCmd() :
  CATStateCommand ("HidePathCmd", CATDlgEngOneShot, CATCommandModeExclusive) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
  ,_Indication(NULL)
{
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
HidePathCmd::~HidePathCmd()
{
   if (_Indication != NULL) 
      _Indication->RequestDelayedDestruction();
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void HidePathCmd::BuildGraph()
{


  // TODO: Define the StateChart 
  // ---------------------------
  _Indication = new CATIndicationAgent ("Indication");
  CATMathPlane PlaneXY;
  _Indication -> SetMathPlane (PlaneXY);
  CATDialogState * initialState = GetInitialState("initialState");
  initialState -> AddDialogAgent (_Indication);
  
  AddTransition( initialState, NULL, 
                 IsOutputSetCondition (_Indication),
                 Action ((ActionMethod) &HidePathCmd::ActionOne));
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean HidePathCmd::ActionOne( void *data )
{
  // TODO: Define the action associated with the transition 
  // ------------------------------------------------------
	CATPPRProcess* pPPRProcess = CATPPRProcess::GetInstance();
	pPPRProcess->GetPPRRootPointer(pPPRProcess->GetCurrentDocument());
	pPPRProcess->GetPPRMoveActivity(pPPRProcess->FirstLayerActivity);
	pPPRProcess->ShowOrHideActivity();

  return TRUE;
}
