// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATAppSettings.h
// Header definition of CATAppSettings
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATAppSettings_H
#define CATAppSettings_H

#include "ObjectBaseMdl.h"
#include "CATStringObject.h"
#include "stdafx.h"

class ExportedByObjectBaseMdl CATAppSettings: public CATStringObject
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATAppSettings ();
     virtual ~CATAppSettings ();

  // Copy constructor and equal operator
  // -----------------------------------
  CATAppSettings (CATAppSettings &);
  CATAppSettings& operator=(CATAppSettings&);

  static int m_nFont;
  static int m_nColor;
  static int m_nSize;
  static int m_nFigure;
  static int m_nPosition;

  static bool GetSettings();

};

//-----------------------------------------------------------------------

#endif
