// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATModelGenerator.h
// Header definition of CATModelGenerator
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATModelGenerator_H
#define CATModelGenerator_H

#include "VBAScriptMdl.h"
#include "CATVBAScript.h"
#include "stdafx.h"

class CATPPRProcess;
class CATProcessFile;

class ExportedByVBAScriptMdl CATModelGenerator: public CATVBAScript
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATModelGenerator ();
     virtual ~CATModelGenerator ();

  public:
	 static CATModelGenerator* GetInstance();
  public:
	 static CATModelGenerator* m_pGenerator;

	 CATPPRProcess	*pProcess;
	 CATProcessFile *pProcessFile;

  // Copy constructor and equal operator
  // -----------------------------------
  CATModelGenerator (CATModelGenerator &);
  CATModelGenerator& operator=(CATModelGenerator&);

  //生成工序当前的模型
  CATBoolean GenerateHSFAndCGRModel(CString strName);
  //生成HSF模型
  CATBoolean GenerateHSF(CString strPath,CString strName,int Count,CString strType);

};

//-----------------------------------------------------------------------

#endif
