// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATPPRStepModel.h
// Header definition of CATPPRStepModel
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Nov 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATPPRStepModel_H
#define CATPPRStepModel_H

#include "ProcessModelMdl.h"
#include "CATPPRProcess.h"

class ExportedByProcessModelMdl CATPPRStepModel: public CATPPRProcess
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATPPRStepModel ();
     virtual ~CATPPRStepModel ();

  // Copy constructor and equal operator
  // -----------------------------------
  CATPPRStepModel (CATPPRStepModel &);
  CATPPRStepModel& operator=(CATPPRStepModel&);

  //TabPageProcess
  CATUnicodeString StepNum;//工步编号
  CATUnicodeString StepName;//工步名称
  CATUnicodeString StepStart;//开始时间
  CATUnicodeString StepEnd;//结束时间
  CATUnicodeString StepContent;//工步内容
  CATUnicodeString StepRemark;//工步备注
  //TabPageMaterial
  CATUnicodeString StepMaterialNum;//材料编号
  CATUnicodeString StepMaterialName;//材料名称
  CATUnicodeString StepMaterialRemark;//材料备注
  //TabPageToolAndEqui
  CATUnicodeString StepEquiName;//设备名称
  CATUnicodeString StepEquiVersion;//设备型号
  CATUnicodeString StepEquiNum;//工装号
  CATUnicodeString StepSpecEqui;//专用工装
  CATUnicodeString StepSpecTool;//专用工具
  CATUnicodeString StepSpecFixture;//专用夹具
  CATUnicodeString StepSpecGage;//专用量具
  CATUnicodeString StepEquiRemark;//备注
  //Move Activity
  CArray<MoveActivity*,MoveActivity*> MoveArray;//可能存在多个Move
  //可能存在子工步
  CArray<CATPPRStepModel*,CATPPRStepModel*> PPRStepArray;

};

//-----------------------------------------------------------------------

#endif
