// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATProcessNotes.h
// Header definition of CATProcessNotes
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATProcessNotes_H
#define CATProcessNotes_H

#include "ProcessNotesMdl.h"
#include "CATStringObject.h"
#include "stdafx.h"

typedef struct _structPPRSubtitle
{
	CString strNum;
	double movestart;//开始时间
	double moveend;//结束时间
	CString strSubtitle;//字幕
}PPRSubtitle;

class ExportedByProcessNotesMdl CATProcessNotes: public CATStringObject
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATProcessNotes ();
     virtual ~CATProcessNotes ();

public:
	static CATProcessNotes* GetInstance();
public:
	static CATProcessNotes* m_pProcessNotes;

	CString m_strFont;//字体
	CString m_strColor;//颜色
	CString m_strSize;//大小
	CString m_strFigure;//字形
	CString m_strPosition;//位置
	CString m_strSetUp;//总体设置

	CArray<PPRSubtitle*,PPRSubtitle*> ProcessSubtitle;

  // Copy constructor and equal operator
  // -----------------------------------
  CATProcessNotes (CATProcessNotes &);
  CATProcessNotes& operator=(CATProcessNotes&);

  //获取字幕设置
  CATBoolean GetSetUpInfo(CATUnicodeString strFont,CATUnicodeString strColor,CATUnicodeString strSize,CATUnicodeString strFigure,CATUnicodeString strPosition);
  //获取字幕字体
  CString GetSubtitleFont(CATUnicodeString strFont);
  //获取字幕颜色
  CString GetSubtitleColor(CATUnicodeString strColor);
  //获取字幕大小
  CString GetSubtitleSize(CATUnicodeString strSize);
  //获取字幕字形
  CString GetSubtitleFigure(CATUnicodeString strFigure);
  //获取字幕位置
  CString GetSubtitlePosition(CATUnicodeString strPosition);
  //生成字幕文件
  CATBoolean GenerateSubtitles(CATUnicodeString strStart,CATUnicodeString strEnd,CATUnicodeString strContent,CATUnicodeString strPath);
  //从指定路径获得字幕文件
  CATBoolean GetSubtitles(CATUnicodeString strPath);
  //获得总时间
  CATBoolean GetStartAndEndTime(CString strTemp,PPRSubtitle* pSubtitle);
  //判断是否已经存在
  CATBoolean GetRefreshFlag(double start,double end,CString strContent);

};

//-----------------------------------------------------------------------

#endif
