// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATReportForm.h
// Header definition of CATReportForm
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATReportForm_H
#define CATReportForm_H

#include "FileManagerMdl.h"
#include "CATProcessFile.h"
#include "CATPPRProcess.h"
#include "CATPPRProcessModel.h"
#include "stdafx.h"
#include "afxcmn.h"
#include "locale.h"

class ExportedByFileManagerMdl CATReportForm: public CATProcessFile
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATReportForm ();
     virtual ~CATReportForm ();

  // Copy constructor and equal operator
  // -----------------------------------
  CATReportForm (CATReportForm &);
  CATReportForm& operator=(CATReportForm&);

  CATBoolean OutputExcel(CArray<CATPPRProcessModel*,CATPPRProcessModel*>& PPRProcessArray);
  CATBoolean OutputHtml(CArray<CATPPRProcessModel*,CATPPRProcessModel*>& PPRProcessArray);

};

//-----------------------------------------------------------------------

#endif
