// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATVideoFile.h
// Header definition of CATVideoFile
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATVideoFile_H
#define CATVideoFile_H

#include "FileManagerMdl.h"
#include "CATFile.h"

class ExportedByFileManagerMdl CATVideoFile: public CATFile
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATVideoFile ();
     virtual ~CATVideoFile ();

public:
	static CATVideoFile* GetInstance();
public:
	static CATVideoFile* m_pVideoFile;

  // Copy constructor and equal operator
  // -----------------------------------
  CATVideoFile (CATVideoFile &);
  CATVideoFile& operator=(CATVideoFile&);

};

//-----------------------------------------------------------------------

#endif
