// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATVBAScript.h
// Header definition of CATVBAScript
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATVBAScript_H
#define CATVBAScript_H

#include "CATStringObject.h"
#include "CATScriptUtilities.h"
#include "CATAutoConversions.h"
#include "VBAScriptMdl.h"
#include "CATFile.h"
#include "stdafx.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href CATVBAScript constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new CATVBAScript;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByVBAScriptMdl CATVBAScript: public CATStringObject
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATVBAScript ();
     virtual ~CATVBAScript ();

  // Copy constructor and equal operator
  // -----------------------------------
  CATVBAScript (CATVBAScript &);
  CATVBAScript& operator=(CATVBAScript&);

  CATFile*		pFile;

  //改写CgrConversion.catvbs
  CATBoolean SetScriptContent(CString strPath,CString strName);
  //改写CgrConversion.catvbs
  CATBoolean SetScriptContent(CArray<CString,CString>& strPathArray,CString strPath);
  //改写CgrAndHsf.catvbs
  CATBoolean SetScriptContent(CString strPath,CString strName,int Count,CString strType);
  //执行一个宏命令
  void ExecuteCATScript(CATUnicodeString strName);

};

//-----------------------------------------------------------------------

#endif
