// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATModelGenerator.cpp
// Header definition of CATModelGenerator
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CATModelGenerator.h"
#include "CATPPRProcess.h"
#include "CATProcessFile.h"
#include "shlwapi.h"

#pragma comment(lib,"Shlwapi.lib")

CATImplementClass( CATModelGenerator,
                   Implementation, 
                   CATVBAScript,
                   CATNull );
 
CATModelGenerator* CATModelGenerator::m_pGenerator = NULL;
//-----------------------------------------------------------------------------
// CATModelGenerator : constructor
//-----------------------------------------------------------------------------
CATModelGenerator::CATModelGenerator():
    CATVBAScript()
{
	pProcess = CATPPRProcess::GetInstance();
	pProcessFile = CATProcessFile::GetInstance();
}

//-----------------------------------------------------------------------------
// CATModelGenerator : destructor
//-----------------------------------------------------------------------------
CATModelGenerator::~CATModelGenerator()
{
}
 
//-----------------------------------------------------------------------------
// CATModelGenerator : copy constructor
//-----------------------------------------------------------------------------
CATModelGenerator::CATModelGenerator(CATModelGenerator& original):
   CATVBAScript(original)
{
}
 
//-----------------------------------------------------------------------------
// CATModelGenerator : equal operator
//-----------------------------------------------------------------------------
CATModelGenerator& CATModelGenerator::operator=(CATModelGenerator& original)
{
   CATVBAScript::operator=(original);
   return *this;
}

CATModelGenerator* CATModelGenerator::GetInstance()
{
	if (m_pGenerator == NULL)
	{
		m_pGenerator = new CATModelGenerator();
	}
	return m_pGenerator;//返回唯一的指针
}

CATBoolean CATModelGenerator::GenerateHSFAndCGRModel(CString strName)
{
	CString strContent;
	CString strPath = GetProgramPath();
	strPath = strPath + _T("\\Settings.txt");
	CStdioFile fifFile(strPath,CFile::modeRead);
	fifFile.ReadString(strContent);
	fifFile.Close();
	//以上获取当前工程的目录
	strContent = strContent + _T("\\Model\\") + strName;
	if (!PathFileExists(strContent))
	{
		::CreateDirectory(strContent,NULL);
	}
	CString string = strContent + _T("\\*.cgr");
	CStringArray strNameArray;
	CStringArray strPathArray;
	int count = pProcessFile->GetFileCount(string,strPathArray,strNameArray);
	//以上获取当前文件夹下的模型数量
	SetScriptContent(strContent,strName,count,_T("cgr"));
	ExecuteCATScript("CgrAndHsf.catvbs");
	//SetScriptContent(strContent,strName,count,_T("3dxml"));
	//ExecuteCATScript("CgrAndHsf.catvbs");
	AfxMessageBox(_T("成功创建工序模型！"));

	return TRUE;
}
