// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// PathManagerAddin.h
// Provide implementation to interface
//    CATIWSPROCAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIWSPROCAddin

//End CAA2 Wizard Generation Report
//
//  Nov 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef PathManagerAddin_H
#define PathManagerAddin_H

class CATCmdContainer;
#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIWSPROCAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class PathManagerAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     PathManagerAddin ();
     virtual ~PathManagerAddin ();

	 void CreateCommands();
	 CATCmdContainer* CreateToolbars();


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  PathManagerAddin (PathManagerAddin &);
  PathManagerAddin& operator=(PathManagerAddin&);

};

//-----------------------------------------------------------------------

#endif
