// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATIntegratedInterface.cpp
// Header definition of CATIntegratedInterface
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CATIntegratedInterface.h"
 
CATIntegratedInterface* CATIntegratedInterface::m_pIntegratedInterface = NULL;
CATImplementClass( CATIntegratedInterface,
                   Implementation, 
                   CATProcessFile,
                   CATNull );
 
//-----------------------------------------------------------------------------
// CATIntegratedInterface : constructor
//-----------------------------------------------------------------------------
CATIntegratedInterface::CATIntegratedInterface():
    CATProcessFile()
{
}

//-----------------------------------------------------------------------------
// CATIntegratedInterface : destructor
//-----------------------------------------------------------------------------
CATIntegratedInterface::~CATIntegratedInterface()
{
}
 
CATIntegratedInterface* CATIntegratedInterface::GetInstance()
{
	if (m_pIntegratedInterface == NULL)
	{
		m_pIntegratedInterface = new CATIntegratedInterface();
	}
	return m_pIntegratedInterface;
}

//-----------------------------------------------------------------------------
// CATIntegratedInterface : copy constructor
//-----------------------------------------------------------------------------
CATIntegratedInterface::CATIntegratedInterface(CATIntegratedInterface& original):
   CATProcessFile(original)
{
}
 
//-----------------------------------------------------------------------------
// CATIntegratedInterface : equal operator
//-----------------------------------------------------------------------------
CATIntegratedInterface& CATIntegratedInterface::operator=(CATIntegratedInterface& original)
{
   CATProcessFile::operator=(original);
   return *this;
}
 
