// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATImageFile.cpp
// Header definition of CATImageFile
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CATImageFile.h"
 
CATImageFile* CATImageFile::m_pImageFile = NULL;
CATImplementClass( CATImageFile,
                   Implementation, 
                   CATFile,
                   CATNull );
 
//-----------------------------------------------------------------------------
// CATImageFile : constructor
//-----------------------------------------------------------------------------
CATImageFile::CATImageFile():
    CATFile()
{
}

//-----------------------------------------------------------------------------
// CATImageFile : destructor
//-----------------------------------------------------------------------------
CATImageFile::~CATImageFile()
{
}
 
CATImageFile* CATImageFile::GetInstance()
{
	if (m_pImageFile == NULL)
	{
		m_pImageFile = new CATImageFile();
	}
	return m_pImageFile;
}

//-----------------------------------------------------------------------------
// CATImageFile : copy constructor
//-----------------------------------------------------------------------------
CATImageFile::CATImageFile(CATImageFile& original):
   CATFile(original)
{
}
 
//-----------------------------------------------------------------------------
// CATImageFile : equal operator
//-----------------------------------------------------------------------------
CATImageFile& CATImageFile::operator=(CATImageFile& original)
{
   CATFile::operator=(original);
   return *this;
}
 
