// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATVideoFile.cpp
// Header definition of CATVideoFile
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CATVideoFile.h"
 
CATVideoFile* CATVideoFile::m_pVideoFile = NULL;
CATImplementClass( CATVideoFile,
                   Implementation, 
                   CATFile,
                   CATNull );
 
//-----------------------------------------------------------------------------
// CATVideoFile : constructor
//-----------------------------------------------------------------------------
CATVideoFile::CATVideoFile():
    CATFile()
{
}

//-----------------------------------------------------------------------------
// CATVideoFile : destructor
//-----------------------------------------------------------------------------
CATVideoFile::~CATVideoFile()
{
}
 
CATVideoFile* CATVideoFile::GetInstance()
{
	if (m_pVideoFile == NULL)
	{
		m_pVideoFile = new CATVideoFile();
	}
	return m_pVideoFile;
}
//-----------------------------------------------------------------------------
// CATVideoFile : copy constructor
//-----------------------------------------------------------------------------
CATVideoFile::CATVideoFile(CATVideoFile& original):
   CATFile(original)
{
}
 
//-----------------------------------------------------------------------------
// CATVideoFile : equal operator
//-----------------------------------------------------------------------------
CATVideoFile& CATVideoFile::operator=(CATVideoFile& original)
{
   CATFile::operator=(original);
   return *this;
}
 
