// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CDlgBITCgrConversion.cpp
// The dialog : CDlgBITCgrConversion
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CDlgBITCgrConversion.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef CDlgBITCgrConversion_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CDlgBITCgrConversion::CDlgBITCgrConversion() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"CDlgBITCgrConversion",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _EditorCGRAddress = NULL;
 _PushButtonCGRAddress = NULL;
 _FrameMacroAddress = NULL;
 _EditorMacroAddress = NULL;
 _FrameCurrentMarcoCode = NULL;
 _EditorCurrentMarcoCode = NULL;
 _RadioButtonProduct = NULL;
 _RadioButtonPart = NULL;
 _EditorCATPartFile = NULL;
 _PushButtonBrowsePart = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CDlgBITCgrConversion::~CDlgBITCgrConversion()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _EditorCGRAddress = NULL;
 _PushButtonCGRAddress = NULL;
 _FrameMacroAddress = NULL;
 _EditorMacroAddress = NULL;
 _FrameCurrentMarcoCode = NULL;
 _EditorCurrentMarcoCode = NULL;
 _RadioButtonProduct = NULL;
 _RadioButtonPart = NULL;
 _EditorCATPartFile = NULL;
 _PushButtonBrowsePart = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}

void CDlgBITCgrConversion::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridRowResizable(4,1);
 SetGridColumnResizable(0,1);
 SetGridColumnResizable(1,1);
 _EditorCGRAddress = new CATDlgEditor(this, "EditorCGRAddress");
_EditorCGRAddress -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonCGRAddress = new CATDlgPushButton(this, "PushButtonCGRAddress");
_PushButtonCGRAddress -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _FrameMacroAddress = new CATDlgFrame(this, "FrameMacroAddress", CATDlgGridLayout);
_FrameMacroAddress -> SetGridConstraints(3, 0, 2, 1, CATGRID_4SIDES);
 _FrameMacroAddress -> SetGridRowResizable(0,1);
 _FrameMacroAddress -> SetGridColumnResizable(0,1);
 _EditorMacroAddress = new CATDlgEditor(_FrameMacroAddress, "EditorMacroAddress", CATDlgEdtReadOnly);
_EditorMacroAddress -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrameCurrentMarcoCode = new CATDlgFrame(this, "FrameCurrentMarcoCode", CATDlgGridLayout);
_FrameCurrentMarcoCode -> SetGridConstraints(4, 0, 2, 1, CATGRID_4SIDES);
 _FrameCurrentMarcoCode -> SetGridRowResizable(0,1);
 _FrameCurrentMarcoCode -> SetGridColumnResizable(0,1);
 _EditorCurrentMarcoCode = new CATDlgEditor(_FrameCurrentMarcoCode, "EditorCurrentMarcoCode", CATDlgEdtMultiline);
_EditorCurrentMarcoCode -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _RadioButtonProduct = new CATDlgRadioButton(this, "RadioButtonProduct");
_RadioButtonProduct -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _RadioButtonPart = new CATDlgRadioButton(this, "RadioButtonPart");
_RadioButtonPart -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _EditorCATPartFile = new CATDlgEditor(this, "EditorCATPartFile");
_EditorCATPartFile -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonBrowsePart = new CATDlgPushButton(this, "PushButtonBrowsePart");
_PushButtonBrowsePart -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION
CATUnicodeString strMacroAddress = "C:\\Temp\\宏目录1\\CgrConversion.catvbs";
_EditorMacroAddress->SetLine(strMacroAddress,0);
pStringObject = CATStringObject::GetInstance();
pFile = CATFile::GetInstance();
_RadioButtonProduct->SetState(CATDlgCheck);
_EditorCATPartFile->SetSensitivity(CATDlgDisable);
_PushButtonBrowsePart->SetSensitivity(CATDlgDisable);
strFlag = _T("Product");
//CAA2 WIZARD CALLBACK DECLARATION SECTION
     AddAnalyseNotificationCB (_RadioButtonPart, 
                               _RadioButtonPart->GetRadBModifyNotification(),
                               (CATCommandMethod)&CDlgBITCgrConversion::OnRadioButtonPartRadBModifyNotification,
                               NULL);
     AddAnalyseNotificationCB (_RadioButtonProduct, 
                               _RadioButtonProduct->GetRadBModifyNotification(),
                               (CATCommandMethod)&CDlgBITCgrConversion::OnRadioButtonProductRadBModifyNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonBrowsePart, 
                               _PushButtonBrowsePart->GetPushBActivateNotification(),
                               (CATCommandMethod)&CDlgBITCgrConversion::OnPushButtonBrowsePartPushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonCGRAddress, 
                               _PushButtonCGRAddress->GetPushBActivateNotification(),
                               (CATCommandMethod)&CDlgBITCgrConversion::OnPushButtonCGRAddressPushBActivateNotification,
                               NULL);
//END CAA2 WIZARD CALLBACK DECLARATION SECTION
//修改窗体位置和大小
CATDlgWindow *pFrmWindow = NULL;
pFrmWindow = (CATApplicationFrame::GetApplicationFrame())->GetApplicationDocument();
DRECT rect;
pFrmWindow->GetRectDimensions(&rect);
int width = 700;
int height = 300;
this->SetRectDimensions(rect.dx-width,(rect.dy-height)/2,height,width);

}

//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonCGRAddress
//-------------------------------------------------------------------------
void CDlgBITCgrConversion::OnRadioButtonProductRadBModifyNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	// Add your code here
	_EditorCATPartFile->SetSensitivity(CATDlgDisable);
	_PushButtonBrowsePart->SetSensitivity(CATDlgDisable);
	strFlag = _T("Product");
}

//-------------------------------------------------------------------------
// Callback on RadBModify of _RadioButtonPart
//-------------------------------------------------------------------------
void CDlgBITCgrConversion::OnRadioButtonPartRadBModifyNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	// Add your code here
	_EditorCATPartFile->SetSensitivity(CATDlgEnable);
	_PushButtonBrowsePart->SetSensitivity(CATDlgEnable);
	strFlag = _T("Part");
}

void CDlgBITCgrConversion::OnPushButtonCGRAddressPushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
	strCGRPath = pFile->OpenOneFolder();
	_EditorCGRAddress->SetLine(pStringObject->ConvertToCATString(strCGRPath));
}

void CDlgBITCgrConversion::OnPushButtonBrowsePartPushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	// Add your code here
	pFile->OpenOneOrMoreFiles(_T(".CATPart"),PartPathArray);
	CString strAllPath = _T("");
	for (int j=0; j<PartPathArray.GetSize(); j++)
	{
		strAllPath = strAllPath + PartPathArray.GetAt(j) + _T(";");
	}
	_EditorCATPartFile->SetLine(pStringObject->ConvertToCATString(strAllPath));
}

//-------------------------------------------------------------------------
// Callback on RadBModify of _RadioButtonProduct
//-------------------------------------------------------------------------

CATBoolean CDlgBITCgrConversion::GetCurrentMacroCode()
{
	_EditorCurrentMarcoCode->ClearLine();
	CString strScriptPath = _T("C:\\Temp\\宏目录1\\CgrConversion.catvbs");
	CString strScriptCode;
	CStdioFile file(strScriptPath,CFile::modeRead);
	file.ReadString(strScriptCode);
	_EditorCurrentMarcoCode->SetLine(pStringObject->ConvertToCATString(strScriptCode),0);
	file.ReadString(strScriptCode);
	file.ReadString(strScriptCode);
	_EditorCurrentMarcoCode->SetLine(pStringObject->ConvertToCATString(strScriptCode),2);
	file.ReadString(strScriptCode);
	file.ReadString(strScriptCode);
	_EditorCurrentMarcoCode->SetLine(pStringObject->ConvertToCATString(strScriptCode),4);
	file.ReadString(strScriptCode);
	file.ReadString(strScriptCode);
	_EditorCurrentMarcoCode->SetLine(pStringObject->ConvertToCATString(strScriptCode),6);
	file.ReadString(strScriptCode);
	file.ReadString(strScriptCode);
	_EditorCurrentMarcoCode->SetLine(pStringObject->ConvertToCATString(strScriptCode),8);
	file.Close();

	return TRUE;
}

void CDlgBITCgrConversion::ModifyWindowPosition()
{
	//修改窗体位置和大小
	CATDlgWindow *pFrmWindow = NULL;
	pFrmWindow = (CATApplicationFrame::GetApplicationFrame())->GetApplicationDocument();
	DRECT rect;
	pFrmWindow->GetRectDimensions(&rect);
	int width = 800;
	int height = 450;
	this->SetRectDimensions(rect.dx-width,(rect.dy-height)/2,height,width);
}
