// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CDlgAddSubtitle.cpp
// The dialog : CDlgAddSubtitle
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CDlgAddSubtitle.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#include "CATAppSettings.h"

#ifdef CDlgAddSubtitle_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif



//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CDlgAddSubtitle::CDlgAddSubtitle() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"CDlgAddSubtitle",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _TabContainerAddNote = NULL;
 _TabPageAddSubtitle = NULL;
 _Frame013 = NULL;
 _EditorVideoAddress = NULL;
 _LabelStart = NULL;
 _EditorStart = NULL;
 _LabelEnd = NULL;
 _EditorEnd = NULL;
 _PushButtonVideoAddress = NULL;
 _FrameSubtitle = NULL;
 _EditorSubtitle = NULL;
 _TabPageSettings = NULL;
 _FrameType = NULL;
 _ComboType = NULL;
 _FrameColor = NULL;
 _ComboColor = NULL;
 _FrameSize = NULL;
 _ComboSize = NULL;
 _FrameFigure = NULL;
 _ComboFigure = NULL;
 _Frame022 = NULL;
 _ComboContentSize = NULL;
 _CheckButtonAll = NULL;
 _ComboContentPosition = NULL;
 _CheckButtonOne = NULL;
 _PushButtonSave = NULL;
 _FramePosition = NULL;
 _ComboPosition = NULL;
 _Frame005 = NULL;
 _FrameMove = NULL;
 _Label007 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _pFile = CATFile::GetInstance();
 pPPRProcess = new CATPPRProcess();
 int layer = 0;
 pPPRProcess->GetPPRRootPointer(pPPRProcess->GetCurrentDocument());
 pPPRProcess->GetPPRNodeInfo(pPPRProcess->FirstLayerActivity,layer);
 ProcessNodeArray.Copy(pPPRProcess->ProcessNodeArray);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CDlgAddSubtitle::~CDlgAddSubtitle()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _TabContainerAddNote = NULL;
 _TabPageAddSubtitle = NULL;
 _Frame013 = NULL;
 _EditorVideoAddress = NULL;
 _LabelStart = NULL;
 _EditorStart = NULL;
 _LabelEnd = NULL;
 _EditorEnd = NULL;
 _PushButtonVideoAddress = NULL;
 _FrameSubtitle = NULL;
 _EditorSubtitle = NULL;
 _TabPageSettings = NULL;
 _FrameType = NULL;
 _ComboType = NULL;
 _FrameColor = NULL;
 _ComboColor = NULL;
 _FrameSize = NULL;
 _ComboSize = NULL;
 _FrameFigure = NULL;
 _ComboFigure = NULL;
 _Frame022 = NULL;
 _ComboContentSize = NULL;
 _CheckButtonAll = NULL;
 _ComboContentPosition = NULL;
 _CheckButtonOne = NULL;
 _PushButtonSave = NULL;
 _FramePosition = NULL;
 _ComboPosition = NULL;
 _Frame005 = NULL;
 _FrameMove = NULL;
 _Label007 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 if (pTreeCtrl)
 {
	 delete pTreeCtrl;
	 pTreeCtrl = NULL;
 }
}

void CDlgAddSubtitle::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridRowResizable(0,1);
 SetGridColumnResizable(1,1);
 _TabContainerAddNote = new CATDlgTabContainer(this, "TabContainerAddNote");
_TabContainerAddNote -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _TabPageAddSubtitle = new CATDlgTabPage(_TabContainerAddNote, "TabPageAddSubtitle", CATDlgGridLayout);
 _TabPageAddSubtitle -> SetGridRowResizable(1,1);
 _TabPageAddSubtitle -> SetGridColumnResizable(0,1);
 _Frame013 = new CATDlgFrame(_TabPageAddSubtitle, "Frame013", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame013 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame013 -> SetGridRowResizable(1,1);
 _Frame013 -> SetGridColumnResizable(1,1);
 _Frame013 -> SetGridColumnResizable(3,1);
 _EditorVideoAddress = new CATDlgEditor(_Frame013, "EditorVideoAddress");
_EditorVideoAddress -> SetGridConstraints(1, 1, 3, 1, CATGRID_4SIDES);
 _LabelStart = new CATDlgLabel(_Frame013, "LabelStart");
_LabelStart -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _EditorStart = new CATDlgEditor(_Frame013, "EditorStart");
 _EditorStart -> SetVisibleTextWidth(3);
_EditorStart -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _LabelEnd = new CATDlgLabel(_Frame013, "LabelEnd");
_LabelEnd -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _EditorEnd = new CATDlgEditor(_Frame013, "EditorEnd");
 _EditorEnd -> SetVisibleTextWidth(3);
_EditorEnd -> SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);
 _PushButtonVideoAddress = new CATDlgPushButton(_Frame013, "PushButtonVideoAddress");
_PushButtonVideoAddress -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _FrameSubtitle = new CATDlgFrame(_TabPageAddSubtitle, "FrameSubtitle", CATDlgGridLayout);
_FrameSubtitle -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _FrameSubtitle -> SetGridRowResizable(0,1);
 _FrameSubtitle -> SetGridColumnResizable(0,1);
 _EditorSubtitle = new CATDlgEditor(_FrameSubtitle, "EditorSubtitle", CATDlgEdtMultiline);
_EditorSubtitle -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _TabPageSettings = new CATDlgTabPage(_TabContainerAddNote, "TabPageSettings", CATDlgGridLayout);
 _TabPageSettings -> SetGridColumnResizable(0,1);
 _TabPageSettings -> SetGridColumnResizable(1,1);
 _FrameType = new CATDlgFrame(_TabPageSettings, "FrameType", CATDlgGridLayout);
_FrameType -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrameType -> SetGridRowResizable(0,1);
 _FrameType -> SetGridColumnResizable(0,1);
 _ComboType = new CATDlgCombo(_FrameType, "ComboType", CATDlgCmbDropDown);
_ComboType -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrameColor = new CATDlgFrame(_TabPageSettings, "FrameColor", CATDlgGridLayout);
_FrameColor -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _FrameColor -> SetGridColumnResizable(0,1);
 _ComboColor = new CATDlgCombo(_FrameColor, "ComboColor", CATDlgCmbColor|CATDlgCmbDropDown);
_ComboColor -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrameSize = new CATDlgFrame(_TabPageSettings, "FrameSize", CATDlgGridLayout);
_FrameSize -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _FrameSize -> SetGridRowResizable(0,1);
 _FrameSize -> SetGridColumnResizable(0,1);
 _ComboSize = new CATDlgCombo(_FrameSize, "ComboSize");
 _ComboSize -> SetVisibleTextHeight(5);
_ComboSize -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrameFigure = new CATDlgFrame(_TabPageSettings, "FrameFigure", CATDlgGridLayout);
_FrameFigure -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _FrameFigure -> SetGridRowResizable(0,1);
 _FrameFigure -> SetGridColumnResizable(0,1);
 _ComboFigure = new CATDlgCombo(_FrameFigure, "ComboFigure");
 _ComboFigure -> SetVisibleTextHeight(5);
_ComboFigure -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame022 = new CATDlgFrame(_TabPageSettings, "Frame022", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame022 -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _Frame022 -> SetGridRowResizable(0,1);
 _Frame022 -> SetGridColumnResizable(0,1);
 _ComboContentSize = new CATDlgCombo(_Frame022, "ComboContentSize", CATDlgCmbDropDown);
_ComboContentSize -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _CheckButtonAll = new CATDlgCheckButton(_Frame022, "CheckButtonAll");
_CheckButtonAll -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _ComboContentPosition = new CATDlgCombo(_Frame022, "ComboContentPosition", CATDlgCmbDropDown);
_ComboContentPosition -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _CheckButtonOne = new CATDlgCheckButton(_Frame022, "CheckButtonOne");
_CheckButtonOne -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonSave = new CATDlgPushButton(_Frame022, "PushButtonSave");
_PushButtonSave -> SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);
 _FramePosition = new CATDlgFrame(_TabPageSettings, "FramePosition", CATDlgGridLayout);
_FramePosition -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _FramePosition -> SetGridRowResizable(0,1);
 _FramePosition -> SetGridColumnResizable(0,1);
 _ComboPosition = new CATDlgCombo(_FramePosition, "ComboPosition");
 _ComboPosition -> SetVisibleTextHeight(5);
_ComboPosition -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame005 = new CATDlgFrame(this, "Frame005", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame005 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame005 -> SetGridRowResizable(1,1);
 _Frame005 -> SetGridColumnResizable(0,1);
 _FrameMove = new CATDlgFrame(_Frame005, "FrameMove", CATDlgGridLayout);
_FrameMove -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Label007 = new CATDlgLabel(_Frame005, "Label007");
_Label007 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION
CATDlgWindow *pFrmWindow = NULL;
pFrmWindow = (CATApplicationFrame::GetApplicationFrame())->GetApplicationDocument();
DRECT rect;
pFrmWindow->GetRectDimensions(&rect);
int width = 700;
int height = 400;
this->SetRectDimensions((rect.dx-width)/2,(rect.dy-height)/2,height,width);
//字体设置
InitComboFont();
//颜色设置
InitComboColor();
//大小设置
InitComboSize();
//字形设置
InitComboFigure();
//位置设置
InitComboPosition();
//设置不可用
_CheckButtonAll->SetState(CATDlgUncheck);
_CheckButtonOne->SetState(CATDlgUncheck);
_ComboContentSize->SetSensitivity(CATDlgDisable);
_ComboContentPosition->SetSensitivity(CATDlgDisable);
//CAA2 WIZARD CALLBACK DECLARATION SECTION
     AddAnalyseNotificationCB (_PushButtonSave, 
                               _PushButtonSave->GetPushBActivateNotification(),
                               (CATCommandMethod)&CDlgAddSubtitle::OnPushButtonSavePushBActivateNotification,
                               NULL);
     AddAnalyseNotificationCB (_CheckButtonOne, 
                               _CheckButtonOne->GetChkBModifyNotification(),
                               (CATCommandMethod)&CDlgAddSubtitle::OnCheckButtonOneChkBModifyNotification,
                               NULL);
     AddAnalyseNotificationCB (_CheckButtonAll, 
                               _CheckButtonAll->GetChkBModifyNotification(),
                               (CATCommandMethod)&CDlgAddSubtitle::OnCheckButtonSetUpChkBModifyNotification,
                               NULL);
     AddAnalyseNotificationCB (_PushButtonVideoAddress, 
                               _PushButtonVideoAddress->GetPushBActivateNotification(),
                               (CATCommandMethod)&CDlgAddSubtitle::OnPushButtonVideoAddress,
                               NULL);
     AddAnalyseNotificationCB (this, 
                               GetDiaOKNotification(),
                               (CATCommandMethod)&CDlgAddSubtitle::OnCDlgAddSubtitleDiaOKNotification,
                               NULL);
//END CAA2 WIZARD CALLBACK DECLARATION SECTION
GenerateBOMTree(_FrameMove,ProcessNodeArray);
}

void CDlgAddSubtitle::InitComboFont()
{
	_ComboType->SetLine("宋体",0);
	_ComboType->SetLine("微软雅黑",1);
	_ComboType->SetLine("新宋体",2);
	_ComboType->SetLine("幼圆",3);
	_ComboType->SetLine("方正舒体",4);
	_ComboType->SetLine("方正姚体",5);
	_ComboType->SetLine("仿宋",6);
	_ComboType->SetLine("汉仪长仿宋体",7);
	_ComboType->SetLine("黑体",8);
	_ComboType->SetLine("华文彩云",9);
	_ComboType->SetLine("华文仿宋",10);
	_ComboType->SetLine("华文行楷",11);
	_ComboType->SetLine("华文琥珀",12);
	_ComboType->SetLine("华文楷体",13);
	_ComboType->SetLine("华文隶书",14);
	_ComboType->SetLine("华文宋体",15);
	_ComboType->SetLine("华文细黑",16);
	_ComboType->SetLine("华文新魏",17);
	_ComboType->SetLine("华文中宋",18);
	_ComboType->SetLine("楷体",19);
	_ComboType->SetLine("隶书",20);
	//_ComboType->SetLine("","E:\\3DPS\\intel_a\\code\\bin\\HUAWENCAIYUN.bmp",50,12,0);
	_ComboType->SetSelect(CATAppSettings::m_nFont);
}

void CDlgAddSubtitle::InitComboColor()
{
	unsigned char iRed = 0,iGreen = 0,iBlue = 0;
	//_ComboColor->SetLine("白色",0);
	iRed = 255,iGreen = 255,iBlue = 255;
	_ComboColor->SetLine("白色",iRed,iGreen,iBlue,0,CATDlgDataAdd);
	//_ComboColor->SetLine("黑色",1);
	iRed = 0,iGreen = 0,iBlue = 0;
	_ComboColor->SetLine("黑色",iRed,iGreen,iBlue,1,CATDlgDataAdd);
	//_ComboColor->SetLine("绿色",2);
	iRed = 0,iGreen = 255,iBlue = 0;
	_ComboColor->SetLine("绿色",iRed,iGreen,iBlue,2,CATDlgDataAdd);
	//_ComboColor->SetLine("蓝色",3);
	iRed = 0,iGreen = 0,iBlue = 255;
	_ComboColor->SetLine("蓝色",iRed,iGreen,iBlue,3,CATDlgDataAdd);
	//_ComboColor->SetLine("黄色",4);
	iRed = 255,iGreen = 255,iBlue = 0;
	_ComboColor->SetLine("黄色",iRed,iGreen,iBlue,4,CATDlgDataAdd);
	//_ComboColor->SetLine("红色",5);
	iRed = 255,iGreen = 0,iBlue = 0;
	_ComboColor->SetLine("红色",iRed,iGreen,iBlue,5,CATDlgDataAdd);
	//_ComboColor->SetLine("青色",6);
	iRed = 0,iGreen = 255,iBlue = 255;
	_ComboColor->SetLine("青色",iRed,iGreen,iBlue,6,CATDlgDataAdd);
	//_ComboColor->SetLine("灰色",7);
	iRed = 190,iGreen = 190,iBlue = 190;
	_ComboColor->SetLine("灰色",iRed,iGreen,iBlue,7,CATDlgDataAdd);
	//_ComboColor->SetLine("紫色",8);
	iRed = 128,iGreen = 0,iBlue = 128;
	_ComboColor->SetLine("紫色",iRed,iGreen,iBlue,8,CATDlgDataAdd);
	//_ComboColor->SetLine("橙色",9);
	iRed = 255,iGreen = 165,iBlue = 0;
	_ComboColor->SetLine("橙色",iRed,iGreen,iBlue,9,CATDlgDataAdd);
	_ComboColor->SetSelect(CATAppSettings::m_nColor);
}

void CDlgAddSubtitle::InitComboSize()
{
	_ComboSize->SetLine("10",0);
	_ComboSize->SetLine("12",1);
	_ComboSize->SetLine("14",2);
	_ComboSize->SetLine("16",3);
	_ComboSize->SetLine("18",4);
	_ComboSize->SetLine("20",5);
	_ComboSize->SetLine("22",6);
	_ComboSize->SetLine("24",7);
	_ComboSize->SetLine("26",8);
	_ComboSize->SetLine("28",9);
	_ComboSize->SetLine("30",10);
	_ComboSize->SetSelect(CATAppSettings::m_nSize);
	_ComboContentSize->SetLine("10",0);
	_ComboContentSize->SetLine("12",1);
	_ComboContentSize->SetLine("14",2);
	_ComboContentSize->SetLine("16",3);
	_ComboContentSize->SetLine("18",4);
	_ComboContentSize->SetLine("20",5);
	_ComboContentSize->SetLine("22",6);
	_ComboContentSize->SetLine("24",7);
	_ComboContentSize->SetLine("26",8);
	_ComboContentSize->SetLine("28",9);
	_ComboContentSize->SetLine("30",10);
	_ComboContentSize->SetSelect(3);
}

void CDlgAddSubtitle::InitComboFigure()
{
	_ComboFigure->SetLine("常规",0);
	_ComboFigure->SetLine("斜体",1);
	_ComboFigure->SetLine("下划线",2);
	_ComboFigure->SetLine("斜体+下划线",3);
	_ComboFigure->SetSelect(CATAppSettings::m_nFigure);
}

void CDlgAddSubtitle::InitComboPosition()
{
	_ComboPosition->SetLine("左对齐",0);
	_ComboPosition->SetLine("居中",1);
	_ComboPosition->SetLine("右对齐",2);
	_ComboPosition->SetLine("左上对齐",3);
	_ComboPosition->SetLine("上居中",4);
	_ComboPosition->SetLine("右上对齐",5);
	_ComboPosition->SetLine("左中心",6);
	_ComboPosition->SetLine("中心",7);
	_ComboPosition->SetLine("右中心",8);
	_ComboPosition->SetSelect(CATAppSettings::m_nPosition);
	_ComboContentPosition->SetLine("左对齐",0);
	_ComboContentPosition->SetLine("居中",1);
	_ComboContentPosition->SetLine("右对齐",2);
	_ComboContentPosition->SetLine("左上对齐",3);
	_ComboContentPosition->SetLine("上居中",4);
	_ComboContentPosition->SetLine("右上对齐",5);
	_ComboContentPosition->SetLine("左中心",6);
	_ComboContentPosition->SetLine("中心",7);
	_ComboContentPosition->SetLine("右中心",8);
	_ComboContentPosition->SetSelect(5);
}

void CDlgAddSubtitle::InitDialogBox()
{
	_EditorStart->ClearLine();
	_EditorEnd->ClearLine();
	_EditorSubtitle->ClearLine();
}

CATBoolean CDlgAddSubtitle::InitLayerArray()
{
	int layer = pPPRProcess->GetLayerCount(ProcessNodeArray);
	if (layer == 0)
	{
		return FALSE;
	}
	LayerArray.RemoveAll();
	for (int i=1; i<=layer; i++)
	{
		LayerArray.Add(1);
	}

	return TRUE;
}

CATBoolean CDlgAddSubtitle::GenerateBOMTree(CATDlgFrame* frame,CArray<ProcessNode*,ProcessNode*>& ProcessNodeArray)
{
	if (ProcessNodeArray.GetSize() == 0)
	{
		return FALSE;
	}
	InitLayerArray();
	CATUnicodeString strIconPath = pPPRProcess->GetIconAddress("Move.bmp");
	frame->SetGridRowResizable(0,1);
	frame->SetGridColumnResizable(0,1);
	pTreeCtrl = new CAATreeCtrl(frame,"TreeCtrl");
	pTreeCtrl->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
	pTreeCtrl->AddRootTreeNode(pPPRProcess->ConvertToCATString(ProcessNodeArray.GetAt(0)->ProcessName),"");
	CATBaseUnknown *pTreeNode = NULL;
	CATBaseUnknown* pFatherNode = NULL;
	pTreeCtrl->GetRootTreeNodeAt(1,&pTreeNode);
	CString strNameAndNum;
	CString strMove;
	for (int i=1; i<ProcessNodeArray.GetSize(); i++)
	{
		int num = ProcessNodeArray.GetAt(i)->layer - ProcessNodeArray.GetAt(i-1)->layer;
		//同级
		if (num == 0)
		{
			pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
			pTreeNode = pFatherNode;
			strNameAndNum = _T("");
			LayerArray.GetAt(ProcessNodeArray.GetAt(i)->layer-1) = LayerArray.GetAt(ProcessNodeArray.GetAt(i)->layer-1) + 1;
			for (int k=0; k<ProcessNodeArray.GetAt(i)->layer; k++)
			{
				if (k == 0)
				{
					strNameAndNum.Format(_T("%d"),LayerArray.GetAt(0));
				}
				if (k > 0)
				{
					strNameAndNum.Format(_T("%s-%d"),strNameAndNum,LayerArray.GetAt(k));
				}
			}
			ProcessNodeArray.GetAt(i)->ProcessStep = strNameAndNum;
			strNameAndNum = strNameAndNum + _T(".") + ProcessNodeArray.GetAt(i)->ProcessName;
			pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,pPPRProcess->ConvertToCATString(strNameAndNum),"");
			for (int j=0; j<ProcessNodeArray.GetAt(i)->MoveArray.GetSize(); j++)
			{
				strMove.Format(_T("%d.%s"),j+1,ProcessNodeArray.GetAt(i)->MoveArray.GetAt(j)->MoveName);
				pTreeCtrl->AddChildTreeNode(pTreeNode,pPPRProcess->ConvertToCATString(strMove),strIconPath);
			}
		}
		//下一级
		if (num == 1)
		{
			strNameAndNum = _T("");
			for (int k=0; k<ProcessNodeArray.GetAt(i)->layer; k++)
			{
				if (k == 0)
				{
					strNameAndNum.Format(_T("%d"),LayerArray.GetAt(0));
				}
				if (k > 0)
				{
					strNameAndNum.Format(_T("%s-%d"),strNameAndNum,LayerArray.GetAt(k));
				}
			}
			ProcessNodeArray.GetAt(i)->ProcessStep = strNameAndNum;
			strNameAndNum = strNameAndNum + _T(".") + ProcessNodeArray.GetAt(i)->ProcessName;
			pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,pPPRProcess->ConvertToCATString(strNameAndNum),"");
			for (int j=0; j<ProcessNodeArray.GetAt(i)->MoveArray.GetSize(); j++)
			{
				strMove.Format(_T("%d.%s"),j+1,ProcessNodeArray.GetAt(i)->MoveArray.GetAt(j)->MoveName);
				pTreeCtrl->AddChildTreeNode(pTreeNode,pPPRProcess->ConvertToCATString(strMove),strIconPath);
			}
		}
		//上N级
		if (num < 0)
		{
			num = -num;
			for (int j=0; j<=num; j++)
			{
				pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
				pTreeNode = pFatherNode;
			}
			strNameAndNum = _T("");
			for (int m=0; m<num; m++)
			{
				LayerArray.GetAt(ProcessNodeArray.GetAt(i-1)->layer-1-m) = 1;
			}
			LayerArray.GetAt(ProcessNodeArray.GetAt(i)->layer-1) = LayerArray.GetAt(ProcessNodeArray.GetAt(i)->layer-1) + 1;
			for (int k=0; k<ProcessNodeArray.GetAt(i)->layer; k++)
			{
				if (k == 0)
				{
					strNameAndNum.Format(_T("%d"),LayerArray.GetAt(0));
				}
				if (k > 0)
				{
					strNameAndNum.Format(_T("%s-%d"),strNameAndNum,LayerArray.GetAt(k));
				}
			}
			ProcessNodeArray.GetAt(i)->ProcessStep = strNameAndNum;
			strNameAndNum = strNameAndNum + _T(".") + ProcessNodeArray.GetAt(i)->ProcessName;
			pTreeNode = pTreeCtrl->AddChildTreeNode(pTreeNode,pPPRProcess->ConvertToCATString(strNameAndNum),"");
			for (int j=0; j<ProcessNodeArray.GetAt(i)->MoveArray.GetSize(); j++)
			{
				strMove.Format(_T("%d.%s"),j+1,ProcessNodeArray.GetAt(i)->MoveArray.GetAt(j)->MoveName);
				pTreeCtrl->AddChildTreeNode(pTreeNode,pPPRProcess->ConvertToCATString(strMove),strIconPath);
			}
		}
	}
	//设置第一个为选中状态
	int iTreeNodeRank = 1;
	CATBaseUnknown *opTreeNodeObject = new CATBaseUnknown();
	pTreeCtrl->GetRootTreeNodeAt(iTreeNodeRank,&opTreeNodeObject);
	pTreeCtrl->SelectTreeNode(opTreeNodeObject);
	AddCallback(pTreeCtrl,TreeNodeSelectNotif::ClassName(),(CATSubscriberMethod)&CDlgAddSubtitle::OnTreeNodeSelect,NULL);

	return TRUE;
}

void CDlgAddSubtitle::OnTreeNodeSelect(CATCallbackEvent event, void * client, CATNotification * iNotification, CATSubscriberData data, 
										CATCallback callback)
{
	CATBaseUnknown * pTreeNode = NULL;
	CATBaseUnknown * pFatherNode = NULL;
	pTreeCtrl -> GetSelectedTreeNode(&pTreeNode);
	pTreeCtrl->GetFatherTreeNode(pTreeNode,&pFatherNode);
	pTreeCtrl -> GetCertainRootTreeNodeLocate(m_NodeLocate,pTreeNode);
	CATUnicodeString strName;
	CATUnicodeString strFatherName;
	pTreeCtrl->GetTreeNodeText(pTreeNode,strName);
	pTreeCtrl->GetTreeNodeText(pFatherNode,strFatherName);
	int pos = pPPRProcess->ConvertToCString(strName).Find(_T("-"));
	if ((pos != -1)&&(pos < 4))
	{
		int processNum = GetSelectedProcessNode(pPPRProcess->ConvertToCString(strName));
		SetDialogContent(processNum);
	}
	else
	{
		int moveNum = GetMoveNumber(pPPRProcess->ConvertToCString(strName));
		int processNum = GetSelectedProcessNode(pPPRProcess->ConvertToCString(strFatherName));
		SetFocusOn(pTreeCtrl);
		SetDialogContent(moveNum,processNum);
	}
}

int CDlgAddSubtitle::GetSelectedProcessNode(CString strNode)
{
	CString strtemp;
	int start = 0;
	int end = strNode.Find(_T("."));
	strtemp = strNode.Mid(start,end);
	for (int i=0; i<ProcessNodeArray.GetSize(); i++)
	{
		if (strtemp == ProcessNodeArray.GetAt(i)->ProcessStep)
		{
			return i;
		}
	}

	return -1;
}

int CDlgAddSubtitle::GetMoveNumber(CString strMove)
{
	int num = -1;
	CString strtemp;
	int start = 0;
	int end = strMove.Find(_T("."));
	strtemp = strMove.Mid(start,end);
	num = _ttoi(strtemp);

	return num;
}

CATBoolean CDlgAddSubtitle::SetDialogContent(int processnum)
{
	InitDialogBox();
	if (processnum == -1)
	{
		return FALSE;
	}
	if (processnum >= ProcessNodeArray.GetSize())
	{
		return FALSE;
	}
	CATUnicodeString strTime;
	strTime.BuildFromNum(ProcessNodeArray.GetAt(processnum)->beginTime);
	_EditorStart->SetLine(strTime,0);
	strTime.BuildFromNum(ProcessNodeArray.GetAt(processnum)->endTime);
	_EditorEnd->SetLine(strTime,0);

	return TRUE;
}

CATBoolean CDlgAddSubtitle::SetDialogContent(int movenum,int processnum)
{
	InitDialogBox();
	if ((movenum == -1)||(processnum == -1))
	{
		return FALSE;
	}
	if (processnum >= ProcessNodeArray.GetSize())
	{
		return FALSE;
	}
	if ((movenum-1) >= ProcessNodeArray.GetAt(processnum)->MoveArray.GetSize())
	{
		return FALSE;
	}
	CATUnicodeString strTime;
	CString strParts = _T("装配零部件：");
	strTime.BuildFromNum(ProcessNodeArray.GetAt(processnum)->MoveArray.GetAt(movenum-1)->beginTime);
	_EditorStart->SetLine(strTime,0);
	strTime.BuildFromNum(ProcessNodeArray.GetAt(processnum)->MoveArray.GetAt(movenum-1)->endTime);
	_EditorEnd->SetLine(strTime,0);
	if (ProcessNodeArray.GetAt(processnum)->MoveArray.GetAt(movenum-1)->ProcessItemArray.GetSize() == 0)
	{
		strParts = _T("");
	}
	if (ProcessNodeArray.GetAt(processnum)->MoveArray.GetAt(movenum-1)->ProcessItemArray.GetSize() == 1)
	{
		strParts = strParts + ProcessNodeArray.GetAt(processnum)->MoveArray.GetAt(movenum-1)->ProcessItemArray.GetAt(0) + _T(";");
	}
	if (ProcessNodeArray.GetAt(processnum)->MoveArray.GetAt(movenum-1)->ProcessItemArray.GetSize() > 1)
	{
		strParts = strParts + ProcessNodeArray.GetAt(processnum)->MoveArray.GetAt(movenum-1)->ProcessItemArray.GetAt(0) + _T("等");
	}
	_EditorSubtitle->SetLine(pPPRProcess->ConvertToCATString(strParts),0);

	return TRUE;
}

CATUnicodeString CDlgAddSubtitle::GetEditorContent(CATDlgEditor* _Editor)
{
	CATUnicodeString content("");
	CATUnicodeString linecontent("");
	int count = _Editor->GetLineCount();
	for (int i=0; i<count; i++)
	{
		_Editor->GetLine(linecontent,i);
		content = content + linecontent;
	}

	return content;
}

CATUnicodeString CDlgAddSubtitle::GetComboSelectedItem(CATDlgCombo* _Combo)
{
	CATUnicodeString string = "";
	int num = _Combo->GetSelect();
	_Combo->GetLine(string,num);

	return string;
}

void CDlgAddSubtitle::OnCDlgAddSubtitleDiaOKNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
	CATProcessNotes *pProcessNotes = CATProcessNotes::GetInstance();
	pProcessNotes->GetSetUpInfo(GetComboSelectedItem(_ComboType),GetComboSelectedItem(_ComboColor),GetComboSelectedItem(_ComboSize),
		GetComboSelectedItem(_ComboFigure),GetComboSelectedItem(_ComboPosition));
	pProcessNotes->GenerateSubtitles(GetEditorContent(_EditorStart),GetEditorContent(_EditorEnd),GetEditorContent(_EditorSubtitle),GetEditorContent(_EditorVideoAddress));
}

//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonVideoAddress
//-------------------------------------------------------------------------
void CDlgAddSubtitle::OnPushButtonVideoAddress(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
  CString strPath = _pFile->OpenOneFile();
  _EditorVideoAddress->SetLine(pPPRProcess->ConvertToCATString(strPath),0);
}

//-------------------------------------------------------------------------
// Callback on ChkBModify of _CheckButtonSetUp
//-------------------------------------------------------------------------
void CDlgAddSubtitle::OnCheckButtonSetUpChkBModifyNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
	if (_CheckButtonAll->GetState() == CATDlgCheck)
	{
		_ComboContentSize->SetSensitivity(CATDlgEnable);
		_ComboContentPosition->SetSensitivity(CATDlgEnable);
	}
	if (_CheckButtonAll->GetState() == CATDlgUncheck)
	{
		_ComboContentSize->SetSensitivity(CATDlgDisable);
		_ComboContentPosition->SetSensitivity(CATDlgDisable);
	}
}


//-------------------------------------------------------------------------
// Callback on ChkBModify of _CheckButtonOne
//-------------------------------------------------------------------------
void CDlgAddSubtitle::OnCheckButtonOneChkBModifyNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
	if (_CheckButtonOne->GetState() == CATDlgCheck)
	{
		_ComboContentSize->SetSensitivity(CATDlgEnable);
		_ComboContentPosition->SetSensitivity(CATDlgEnable);
	}
	if (_CheckButtonOne->GetState() == CATDlgUncheck)
	{
		_ComboContentSize->SetSensitivity(CATDlgDisable);
		_ComboContentPosition->SetSensitivity(CATDlgDisable);
	}
}

//-------------------------------------------------------------------------
// Callback on PushBActivate of _PushButtonSave
//-------------------------------------------------------------------------
void CDlgAddSubtitle::OnPushButtonSavePushBActivateNotification(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
  // Add your code here
	CString strContent;
	CString strPath = _pFile->GetProgramPath();
	strPath = strPath + _T("\\CAppSettings.ini");
	CStdioFile fifFile(strPath,CFile::modeCreate|CFile::modeReadWrite);
	
	strContent.Format(_T("%d"),_ComboType->GetSelect());
	fifFile.WriteString(strContent);
	fifFile.WriteString(_T("\n"));

	strContent.Format(_T("%d"),_ComboColor->GetSelect());
	fifFile.WriteString(strContent);
	fifFile.WriteString(_T("\n"));

	strContent.Format(_T("%d"),_ComboSize->GetSelect());
	fifFile.WriteString(strContent);
	fifFile.WriteString(_T("\n"));

	strContent.Format(_T("%d"),_ComboFigure->GetSelect());
	fifFile.WriteString(strContent);
	fifFile.WriteString(_T("\n"));

	strContent.Format(_T("%d"),_ComboPosition->GetSelect());
	fifFile.WriteString(strContent);

	fifFile.Close();
}
