// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CgrConversionAddin.cpp
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CgrConversionAddin.h"
#include "CATCreateWorkshop.h" // needed to manage workshop access
#include "CATCommandHeader.h"  // needed to instanciate the header
MacDeclareHeader(CgrConversionHeader); 
 
CATImplementClass(CgrConversionAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 

//-----------------------------------------------------------------------------
// CgrConversionAddin : constructor
//-----------------------------------------------------------------------------
CgrConversionAddin::CgrConversionAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// CgrConversionAddin : destructor
//-----------------------------------------------------------------------------
CgrConversionAddin::~CgrConversionAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------
void CgrConversionAddin::CreateCommands()
{

	// Instantiation of the header class created by the macro MacDeclareHeader -
	// commands are always available and are represented by a push button
	new CgrConversionHeader( "BITCgrConversion","BITCgrConversion","BITCgrConversionCmd",(void *)NULL);
}

CATCmdContainer* CgrConversionAddin::CreateToolbars()
{

	NewAccess        (CATCmdContainer,pToolbar,BITCgrConversion);

	NewAccess        (CATCmdStarter,pCGRStarter,CgrConversionCmd);
	SetAccessCommand (pCGRStarter,"BITCgrConversion");
	SetAccessChild   (pToolbar , pCGRStarter);

	AddToolbarView   (pToolbar,1,Right); // 1 for visible toolbar

	return pToolbar;
}

//TIE or TIEchain definitions
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(CgrConversionAddin);


//Methods implementation

