// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// ProcessAddin.cpp
// Provide implementation to interface
//    CATIWSPROCAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "ProcessAddin.h"
#include "CATCreateWorkshop.h" // needed to manage workshop access
#include "CATCommandHeader.h"  // needed to instanciate the header
MacDeclareHeader(AssemblyProcessHeader); 
 
CATImplementClass(ProcessAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 

//-----------------------------------------------------------------------------
// ProcessAddin : constructor
//-----------------------------------------------------------------------------
ProcessAddin::ProcessAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// ProcessAddin : destructor
//-----------------------------------------------------------------------------
ProcessAddin::~ProcessAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------
void ProcessAddin::CreateCommands()
{

	// Instantiation of the header class created by the macro MacDeclareHeader -
	// commands are always available and are represented by a push button
	new AssemblyProcessHeader( "NewFile","BITProcessModel","NewFileCmd",(void *)NULL);
	new AssemblyProcessHeader( "OpenFile","BITProcessModel","OpenFileCmd",(void *)NULL);
	new AssemblyProcessHeader( "ProcessTreeModel","BITProcessModel","ProcessTreeModelCmd",(void *)NULL);
	new AssemblyProcessHeader( "ProcessModel","BITProcessModel","ProcessModelCmd",(void *)NULL);
	new AssemblyProcessHeader( "StepModel","BITProcessModel","StepModelCmd",(void *)NULL);
	new AssemblyProcessHeader( "OutPutProcess","BITProcessModel","OutPutProcessCmd",(void *)NULL);
	new AssemblyProcessHeader( "AddSubtitle","BITProcessModel","AddSubtitleCmd",(void *)NULL);
	new AssemblyProcessHeader( "ModifyBOMTree","BITProcessModel","ModifyBOMTreeCmd",(void *)NULL);
	new AssemblyProcessHeader( "FilmStarter","BITProcessModel","FilmStarterCmd",(void *)NULL);
}

CATCmdContainer* ProcessAddin::CreateToolbars()
{

	NewAccess        (CATCmdContainer,pToolbar,ProcessPlanning);

	NewAccess        (CATCmdStarter,pNewStarter,NewFileCmd);
	SetAccessCommand (pNewStarter,"NewFile");
	SetAccessChild   (pToolbar , pNewStarter);

	NewAccess        (CATCmdStarter,pOpenStarter,OpenFileCmd);
	SetAccessCommand (pOpenStarter,"OpenFile");
	SetAccessNext   (pNewStarter , pOpenStarter);

	NewAccess        (CATCmdStarter,pProcessStarter,ProcessTreeModelCmd);
	SetAccessCommand (pProcessStarter,"ProcessTreeModel");
	SetAccessNext   (pOpenStarter , pProcessStarter);

	NewAccess        (CATCmdStarter,pModelStarter,ProcessModelCmd);
	SetAccessCommand (pModelStarter,"ProcessModel");
	SetAccessNext   (pProcessStarter , pModelStarter);

	NewAccess        (CATCmdStarter,pStepStarter,StepModelCmd);
	SetAccessCommand (pStepStarter,"StepModel");
	SetAccessNext   (pModelStarter , pStepStarter);

	NewAccess        (CATCmdStarter,pOutPutStarter,OutPutProcessCmd);
	SetAccessCommand (pOutPutStarter,"OutPutProcess");
	SetAccessNext   (pStepStarter , pOutPutStarter);

	NewAccess        (CATCmdStarter,pSubtitle,AddSubtitleCmd);
	SetAccessCommand (pSubtitle,"AddSubtitle");
	SetAccessNext   (pOutPutStarter , pSubtitle);

	NewAccess        (CATCmdStarter,pModifyStarter,ModifyBOMTreeCmd);
	SetAccessCommand (pModifyStarter,"ModifyBOMTree");
	SetAccessNext   (pSubtitle , pModifyStarter);

	NewAccess        (CATCmdStarter,pFilmStarter,FilmStarterCmd);
	SetAccessCommand (pFilmStarter,"FilmStarter");
	SetAccessNext   (pModifyStarter , pFilmStarter);

	AddToolbarView   (pToolbar,1,Right); // 1 for visible toolbar

	return pToolbar;
}

//TIE or TIEchain definitions
#include "TIE_CATIWSPROCAddin.h"
TIE_CATIWSPROCAddin(ProcessAddin);


//Methods implementation

