// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// ProcessTreeModelCmd.cpp
// The state chart based command: ProcessTreeModelCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "ProcessTreeModelCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( ProcessTreeModelCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
ProcessTreeModelCmd::ProcessTreeModelCmd() :
  CATStateCommand ("ProcessTreeModelCmd", CATDlgEngOneShot, CATCommandModeExclusive) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
  ,_Indication(NULL)
{
	pDlgProcessTreeModel = new CDlgProcessTreeModel();
	pDlgProcessTreeModel->Build();
	pDlgProcessTreeModel->SetVisibility(CATDlgShow);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
ProcessTreeModelCmd::~ProcessTreeModelCmd()
{
   if (_Indication != NULL) 
      _Indication->RequestDelayedDestruction();

   if (pDlgProcessTreeModel != NULL) 
   {
	   pDlgProcessTreeModel->RequestDelayedDestruction();
	   pDlgProcessTreeModel = NULL;
   }
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void ProcessTreeModelCmd::BuildGraph()
{


  // TODO: Define the StateChart 
  // ---------------------------
  _Indication = new CATIndicationAgent ("Indication");
  CATMathPlane PlaneXY;
  _Indication -> SetMathPlane (PlaneXY);
  CATDialogState * initialState = GetInitialState("initialState");
  initialState -> AddDialogAgent (_Indication);
  
  AddTransition( initialState, NULL, 
                 IsOutputSetCondition (_Indication),
                 Action ((ActionMethod) &ProcessTreeModelCmd::ActionOne));
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean ProcessTreeModelCmd::ActionOne( void *data )
{
  // TODO: Define the action associated with the transition 
  // ------------------------------------------------------

  return TRUE;
}
