// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATPPRProcessModel.cpp
// Header definition of CATPPRProcessModel
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Nov 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CATPPRProcessModel.h"
 
CATImplementClass( CATPPRProcessModel,
                   Implementation, 
                   CATPPRProcess,
                   CATNull );
 
//-----------------------------------------------------------------------------
// CATPPRProcessModel : constructor
//-----------------------------------------------------------------------------
CATPPRProcessModel::CATPPRProcessModel():
    CATPPRProcess()
{
}

//-----------------------------------------------------------------------------
// CATPPRProcessModel : destructor
//-----------------------------------------------------------------------------
CATPPRProcessModel::~CATPPRProcessModel()
{
}
 
//-----------------------------------------------------------------------------
// CATPPRProcessModel : copy constructor
//-----------------------------------------------------------------------------
CATPPRProcessModel::CATPPRProcessModel(CATPPRProcessModel& original):
   CATPPRProcess(original)
{
}
 
//-----------------------------------------------------------------------------
// CATPPRProcessModel : equal operator
//-----------------------------------------------------------------------------
CATPPRProcessModel& CATPPRProcessModel::operator=(CATPPRProcessModel& original)
{
   CATPPRProcess::operator=(original);
   return *this;
}
 
