// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATPPRStepModel.cpp
// Header definition of CATPPRStepModel
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Nov 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#include "CATPPRStepModel.h"
 
CATImplementClass( CATPPRStepModel,
                   Implementation, 
                   CATPPRProcess,
                   CATNull );
 
//-----------------------------------------------------------------------------
// CATPPRStepModel : constructor
//-----------------------------------------------------------------------------
CATPPRStepModel::CATPPRStepModel():
    CATPPRProcess()
{
}

//-----------------------------------------------------------------------------
// CATPPRStepModel : destructor
//-----------------------------------------------------------------------------
CATPPRStepModel::~CATPPRStepModel()
{
}
 
//-----------------------------------------------------------------------------
// CATPPRStepModel : copy constructor
//-----------------------------------------------------------------------------
CATPPRStepModel::CATPPRStepModel(CATPPRStepModel& original):
   CATPPRProcess(original)
{
}
 
//-----------------------------------------------------------------------------
// CATPPRStepModel : equal operator
//-----------------------------------------------------------------------------
CATPPRStepModel& CATPPRStepModel::operator=(CATPPRStepModel& original)
{
   CATPPRProcess::operator=(original);
   return *this;
}
 
