// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// CDlgNewDisAssembly.h
// The dialog : CDlgNewDisAssembly
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CDlgNewDisAssembly_H
#define CDlgNewDisAssembly_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CAATreeCtrl.h"
#include "TreeNodeSelectNotif.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class CDlgNewDisAssembly: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CDlgNewDisAssembly, CATDlgDialog )

  public:

  CDlgNewDisAssembly();
  virtual ~CDlgNewDisAssembly();

  void Build ();
  //生成BOM树
  CATBoolean GenerateBOMTree(CATDlgFrame* frame);
  //反转BOM树
  CATBoolean GenerateRBOMTree(CATDlgFrame* frame);

  protected:
  /**
  * Callback on DiaCANCEL of _CDlgNewDisAssembly
  *
  * <br><b>Role</b>: This method handles the DiaCANCEL event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnCDlgNewDisAssemblyDiaCANCELNotification
  *
  *
  */
  virtual void OnCDlgNewDisAssemblyDiaCANCELNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  /**
  * Callback on DiaOK of _CDlgNewDisAssembly
  *
  * <br><b>Role</b>: This method handles the DiaOK event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnCDlgNewDisAssemblyDiaOKNotification
  *
  *
  */
  virtual void OnCDlgNewDisAssemblyDiaOKNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgLabel*      _Label002;
 CATDlgEditor*      _Editor003;
 CATDlgLabel*      _Label004;
 CATDlgEditor*      _Editor005;
 CATDlgPushButton*      _PushButton006;
 CATDlgPushButton*      _PushButton007;
 CATDlgFrame*      _Frame009;
 CATDlgFrame*      _Frame010;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
 CAATreeCtrl			*pTreeCtrl;
};

//----------------------------------------------------------------------

#endif
