// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// CDlgModelCredibility.h
// The dialog : CDlgModelCredibility
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CDlgModelCredibility_H
#define CDlgModelCredibility_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CAATreeCtrl.h"
#include "TreeNodeSelectNotif.h"
//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class CDlgModelCredibility: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CDlgModelCredibility, CATDlgDialog )

  public:

  CDlgModelCredibility();
  virtual ~CDlgModelCredibility();

  void Build ();
  //Éú³ÉBOMÊ÷
  CATBoolean GenerateBOMTree(CATDlgFrame* frame);

  protected:
  /**
  * Callback on DiaCANCEL of _CDlgModelCredibility
  *
  * <br><b>Role</b>: This method handles the DiaCANCEL event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnCDlgModelCredibilityDiaCANCELNotification
  *
  *
  */
  virtual void OnCDlgModelCredibilityDiaCANCELNotification (CATCommand *, CATNotification* , CATCommandClientData data);
  /**
  * Callback on DiaOK of _CDlgModelCredibility
  *
  * <br><b>Role</b>: This method handles the DiaOK event and does
  *   a check on ...
  *
  * @param Command [in]
  *   Pointer to the publisher of the event.
  * @param Notification [in]
  *   Pointer to the notification representing the event.
  * @param data [in]
  *   Possible useful data transmitted to the command OnCDlgModelCredibilityDiaOKNotification
  *
  *
  */
  virtual void OnCDlgModelCredibilityDiaOKNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame001;
 CATDlgLabel*      _Label002;
 CATDlgEditor*      _Editor004;
 CATDlgLabel*      _Label005;
 CATDlgEditor*      _Editor008;
 CATDlgLabel*      _Label009;
 CATDlgEditor*      _Editor011;
 CATDlgLabel*      _Label012;
 CATDlgEditor*      _Editor014;
 CATDlgLabel*      _Label015;
 CATDlgEditor*      _Editor017;
 CATDlgLabel*      _Label018;
 CATDlgEditor*      _Editor020;
 CATDlgMultiList*      _MultiList021;
 CATDlgCheckButton*      _CheckButton022;
 CATDlgLabel*      _Label023;
 CATDlgMultiList*      _MultiList024;
 CATDlgMultiList*      _MultiList025;
 CATDlgMultiList*      _MultiList026;
 CATDlgMultiList*      _MultiList027;
 CATDlgMultiList*      _MultiList028;
 CATDlgEditor*      _Editor029;
 CATDlgLabel*      _Label030;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
 CAATreeCtrl			*pTreeCtrl;
};

//----------------------------------------------------------------------

#endif
