// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// ModelCredibilityCmd.h
// The state chart based command: ModelCredibilityCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef ModelCredibilityCmd_H
#define ModelCredibilityCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CDlgModelCredibility.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class ModelCredibilityCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( ModelCredibilityCmd, CATStateCommand )

  public:

  ModelCredibilityCmd();
  virtual ~ModelCredibilityCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();
  virtual CATBoolean  ActionOK(void * data);
  virtual CATBoolean  ActionCancel(void * data);
  virtual CATBoolean  ActionClose(void * data);

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  private:
	  CDlgModelCredibility	* pDlgModelCredibility;
	  CATDialogAgent		* pOkBut,
							* pCancelBut,
							* pCloseBut;
};

//----------------------------------------------------------------------

#endif
