// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// NewDisAssemblyCmd.h
// The state chart based command: NewDisAssemblyCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef NewDisAssemblyCmd_H
#define NewDisAssemblyCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CDlgNewDisAssembly.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class NewDisAssemblyCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( NewDisAssemblyCmd, CATStateCommand )

  public:

  NewDisAssemblyCmd();
  virtual ~NewDisAssemblyCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();
  virtual CATBoolean  ActionOK(void * data);
  virtual CATBoolean  ActionCancel(void * data);
  virtual CATBoolean  ActionClose(void * data);

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  private:

	  CDlgNewDisAssembly	* pDlgNewDisAssembly;
	  CATDialogAgent		* pOkBut,
							* pCancelBut,
							* pCloseBut;
};

//----------------------------------------------------------------------

#endif
