H:\3DPS-256(1)\.\CAATreeCtrlFrm\various\intel_a\HList\PrivateInterfaces.hl
H:\3DPS-256(1)\.\CAATreeCtrlFrm\various\intel_a\HList\ProtectedInterfaces.hl
H:\3DPS-256(1)\.\CAATreeCtrlFrm\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Administration\various\intel_a\HList\PrivateInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Administration\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Administration\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\AdvancedMathematics\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\AdvancedMathematics\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ApplicationFrame\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ApplicationFrame\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\AutomationInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\AutomationInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\BatchInfrastructure\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\BatchInfrastructure\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CAT3DXmlBaseServices\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CAT3DXmlBaseServices\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CAT3DXmlExportTools\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CAT3DXmlExportTools\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CAT3DXmlInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CAT3DXmlInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATDataCompatibilityInfra\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATDataCompatibilityInfra\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATGraphicProperties\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATGraphicProperties\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIAApplicationFrame\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIAApplicationFrame\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIADataBasics\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIADataBasics\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIADataMacFortran\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIADataMacFortran\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATImmWtpInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATImmWtpInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATJavaBridge\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATJavaBridge\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATMatInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATMatInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPDMBase\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPDMBase\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPDMBaseInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPDMBaseInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPLMDictionary\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPLMDictionary\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATRmaInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATRmaInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSmarTeamIntegInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSmarTeamIntegInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSubdivisionApproximation\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSubdivisionApproximation\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSubdivisionMeshOperators\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSubdivisionMeshOperators\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSubdivisionObjects\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATSubdivisionObjects\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATTechnologicalPackageUIItf\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATTechnologicalPackageUIItf\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATV4System\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATV4System\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATVirtualVaultSystem\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATVirtualVaultSystem\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATXDocLinkInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATXDocLinkInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CORBARuntime\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CORBARuntime\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Communications\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Communications\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ComponentsCatalogs\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ComponentsCatalogs\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ComponentsCatalogsInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ComponentsCatalogsInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DMAPSInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DMAPSInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBDpmInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBDpmInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBGanttChart\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBGanttChart\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBGraphEditor\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBGraphEditor\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBResourceBehaviorInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBResourceBehaviorInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBStateInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBStateInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBStateModeler\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DNBStateModeler\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Dialog\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Dialog\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DialogEngine\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DialogEngine\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ENOVaultClientCPP\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\FileMenu\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\FileMenu\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GenericNaming\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GenericNaming\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GeometricObjects\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GeometricObjects\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GeometricObjectsCGM\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GeometricObjectsCGM\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GeometricOperators\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GeometricOperators\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Graph\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Graph\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\HLRBase\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\HLRBase\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InfInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InfInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InteractiveInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InteractiveInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\KnowledgeInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\KnowledgeInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\KnowledgeModeler\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\KnowledgeModeler\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\LiteralFeatures\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\LiteralFeatures\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\LiteralsEditor\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\LiteralsEditor\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mainwin\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mainwin\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mathematics\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mathematics\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\MecModInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\MecModInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Multimedia\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Multimedia\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\NewTopologicalObjects\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\NewTopologicalObjects\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerBase\various\intel_a\HList\PrivateInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerBase\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerBase\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerBaseUI\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerBaseUI\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCATIA\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCATIA\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCollection\various\intel_a\HList\PrivateInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCollection\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCollection\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerNavigator\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerNavigator\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerSystem\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerSystem\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectSpecsModeler\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectSpecsModeler\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolygonalTools\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolygonalTools\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralMathematics\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralMathematics\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralObjects\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralObjects\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralOperators\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralOperators\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralVisualization\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PolyhedralVisualization\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Print\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Print\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PrintBase\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\PrintBase\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProcessPlatformBase\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProcessPlatformBase\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProcessPlatformVisu\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProcessPlatformVisu\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProductStructure\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProductStructure\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProductStructureInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProductStructureInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SketcherInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SketcherInterfaces\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SpecialAPI\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SpecialAPI\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\System\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\System\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Tessellation\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Tessellation\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VBA\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VBA\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Visualization\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Visualization\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VisualizationBase\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VisualizationBase\various\intel_a\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\XMLParser\various\intel_a\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\XMLParser\various\intel_a\HList\PublicInterfaces.hl
