// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAATreeCtrlFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("CATIAApplicationFrame",Protected);
AddPrereqComponent("ProcessPlatformVisu",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
// END WIZARD EDITION ZONE
