// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CDlgAddSubtitle.h
// The dialog : CDlgAddSubtitle
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CDlgAddSubtitle_H
#define CDlgAddSubtitle_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATPPRProcess.h"
#include "CAATreeCtrl.h"
#include "TreeNodeSelectNotif.h"
#include "CATFile.h"
#include "CATProcessNotes.h"
#include "stdafx.h"

class CDlgAddSubtitle: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CDlgAddSubtitle, CATDlgDialog )

  public:

  CDlgAddSubtitle();
  virtual ~CDlgAddSubtitle();

  int m_NodeLocate;

  //Process所有节点信息
  CArray<ProcessNode*,ProcessNode*> ProcessNodeArray;
  //Process所有层
  CArray<int,int> LayerArray;

  void Build ();

  //初始字体设置
  void InitComboFont();
  //初始颜色设置
  void InitComboColor();
  //初始大小设置
  void InitComboSize();
  //初始字形设置
  void InitComboFigure();
  //初始位置设置
  void InitComboPosition();
  //清空对话框的内容
  void InitDialogBox();
  //初始化层
  CATBoolean InitLayerArray();
  //生成BOM树
  CATBoolean GenerateBOMTree(CATDlgFrame* frame,CArray<ProcessNode*,ProcessNode*>& ProcessNodeArray);
  //添加对用户交互选择树形结构控件的响应
  void OnTreeNodeSelect(CATCallbackEvent event,void * client,CATNotification* iNotification,CATSubscriberData data,CATCallback callback);
  //获取当前选中的树节点对应的工序节点
  int GetSelectedProcessNode(CString strNode);
  //获取Move的序号
  int GetMoveNumber(CString strMove);
  //设置对话框的内容,工序或者工步
  CATBoolean SetDialogContent(int processnum);
  //设置对话框的内容，Move
  CATBoolean SetDialogContent(int movenum,int processnum);
  //获取Editor的内容，可能多行
  CATUnicodeString GetEditorContent(CATDlgEditor* _Editor);
  //获取Combo的内容
  CATUnicodeString GetComboSelectedItem(CATDlgCombo* _Combo);

  protected:

  virtual void OnPushButtonSavePushBActivateNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnCheckButtonOneChkBModifyNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnCheckButtonSetUpChkBModifyNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnPushButtonVideoAddress (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnCDlgAddSubtitleDiaOKNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgTabContainer*      _TabContainerAddNote;
 CATDlgTabPage*      _TabPageAddSubtitle;
 CATDlgFrame*      _Frame013;
 CATDlgEditor*      _EditorVideoAddress;
 CATDlgLabel*      _LabelStart;
 CATDlgEditor*      _EditorStart;
 CATDlgLabel*      _LabelEnd;
 CATDlgEditor*      _EditorEnd;
 CATDlgPushButton*      _PushButtonVideoAddress;
 CATDlgFrame*      _FrameSubtitle;
 CATDlgEditor*      _EditorSubtitle;
 CATDlgTabPage*      _TabPageSettings;
 CATDlgFrame*      _FrameType;
 CATDlgCombo*      _ComboType;
 CATDlgFrame*      _FrameColor;
 CATDlgCombo*      _ComboColor;
 CATDlgFrame*      _FrameSize;
 CATDlgCombo*      _ComboSize;
 CATDlgFrame*      _FrameFigure;
 CATDlgCombo*      _ComboFigure;
 CATDlgFrame*      _Frame022;
 CATDlgCombo*      _ComboContentSize;
 CATDlgCheckButton*      _CheckButtonAll;
 CATDlgCombo*      _ComboContentPosition;
 CATDlgCheckButton*      _CheckButtonOne;
 CATDlgPushButton*      _PushButtonSave;
 CATDlgFrame*      _FramePosition;
 CATDlgCombo*      _ComboPosition;
 CATDlgFrame*      _Frame005;
 CATDlgFrame*      _FrameMove;
 CATDlgLabel*      _Label007;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
 CATPPRProcess			*pPPRProcess;
 CAATreeCtrl			*pTreeCtrl;
 CATFile				*_pFile;
};

//----------------------------------------------------------------------

#endif
