// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CDlgFigureReview.h
// The dialog : CDlgFigureReview
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CDlgFigureReview_H
#define CDlgFigureReview_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "stdafx.h"
#include "CATFile.h"

class CAT2DViewer;
class CATViewer;
class CAT2DRep;

class CDlgFigureReview: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CDlgFigureReview, CATDlgDialog )

  public:

  CDlgFigureReview();
  virtual ~CDlgFigureReview();

public:
	static CDlgFigureReview* GetInstance();
public:
	static CDlgFigureReview* m_pFigureReview;

	CATFile		*_pFile;

	bool flag;//工序附图只new一次
	CString strFilePath;
	int Count;//当前模型个数
	int Number;//当前打开的模型编号
	CStringArray strNameArray;
	CStringArray strPathArray;

  void Build ();

  //获取当前视图
  CATViewer* GetCurrentViewer();
  //截取当前视图,并返回视图地址
  CString InterceptCurrentView(CString string);
  CATBoolean CheckProcessFigure(CString strName);
  CATBoolean ProcessFigureReview(CString strProcessName);
  CATBoolean ReviewFigure(CString str);

  protected:

  virtual void OnCDlgFigureReviewDiaCLOSENotification (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnCDlgFigureReviewDiaPREVIEWNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnCDlgFigureReviewDiaCANCELNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  virtual void OnCDlgFigureReviewDiaOKNotification (CATCommand *, CATNotification* , CATCommandClientData data);

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame001;
//END CAA2 WIZARD WIDGET DECLARATION SECTION


//END CAA2 WIZARD WIDGET DECLARATION SECTION
 CAT2DRep *_pRepImage;
 CAT2DViewer *_p2DViewer;
};

//----------------------------------------------------------------------

#endif
