// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// FilmStarterCmd.h
// The state chart based command: FilmStarterCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef FilmStarterCmd_H
#define FilmStarterCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "stdafx.h"

class FilmStarterCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( FilmStarterCmd, CATStateCommand )

  public:

  FilmStarterCmd();
  virtual ~FilmStarterCmd();

  virtual void     BuildGraph();

  CString GetProgramPath();

  private:

};

//----------------------------------------------------------------------

#endif
