// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// OpenFileCmd.h
// The state chart based command: OpenFileCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef OpenFileCmd_H
#define OpenFileCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CDlgOpenFile.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class OpenFileCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( OpenFileCmd, CATStateCommand )

  public:

  OpenFileCmd();
  virtual ~OpenFileCmd();

  virtual void     BuildGraph();

  virtual CATBoolean  ActionOK(void * data);
  virtual CATBoolean  ActionCancel(void * data);
  virtual CATBoolean  ActionClose(void * data);

  private:
	  CDlgOpenFile			* pDlgOpenFile;
	  CATDialogAgent		* pOkBut,
							* pCancelBut,
							* pCloseBut;
};

//----------------------------------------------------------------------

#endif
