// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// ProcessTreeModelCmd.h
// The state chart based command: ProcessTreeModelCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Dec 2016  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef ProcessTreeModelCmd_H
#define ProcessTreeModelCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CDlgProcessTreeModel.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class ProcessTreeModelCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( ProcessTreeModelCmd, CATStateCommand )

  public:

  ProcessTreeModelCmd();
  virtual ~ProcessTreeModelCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  private:

  CATIndicationAgent	* _Indication;

  CDlgProcessTreeModel      * pDlgProcessTreeModel;
};

//----------------------------------------------------------------------

#endif
