// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// ProcessModelCmd.h
// The state chart based command: ProcessModelCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef ProcessModelCmd_H
#define ProcessModelCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CDlgProcessModel.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class ProcessModelCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( ProcessModelCmd, CATStateCommand )

  public:

  ProcessModelCmd();
  virtual ~ProcessModelCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

  virtual CATBoolean  ActionCancel(void * data);
  virtual CATBoolean  ActionClose(void * data);


  private:
	  CATDialogAgent		* pCancelBut,
							* pCloseBut;
	  CDlgProcessModel      * pDlgProcessModel;

};

//----------------------------------------------------------------------

#endif
