// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// StepModelCmd.h
// The state chart based command: StepModelCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Nov 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef StepModelCmd_H
#define StepModelCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CDlgStepModel.h"


//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class StepModelCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( StepModelCmd, CATStateCommand )

  public:

  StepModelCmd();
  virtual ~StepModelCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

  virtual CATBoolean  ActionCancel(void * data);
  virtual CATBoolean  ActionClose(void * data);

  private:
	  CATDialogAgent		* pCancelBut,
							* pCloseBut;
	  CDlgStepModel			* pDlgStepModel;
};

//----------------------------------------------------------------------

#endif
