set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="C:\Program Files\Dassault Systemes\B19\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=C:\Program Files\Dassault Systemes\B19\intel_a
set ADL_SITE_NAME=V5R19_B19
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=C:\Program Files\Dassault Systemes\B19\intel_a\code\command
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\rt\AppData\Roaming
set BLD_HOST_OS=intel_a
set CommonProgramFiles=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-101VI2D
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\intel_a
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\intel_a
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\intel_a
set CSCSkipTestOfMapFileValidity=1
set DSarMakerROOT_PATH=C:\PROGRA~1\DASSAU~1\B19\CATWebDSarMaker
set HOMEDRIVE=C:
set HOMEPATH=\Users\rt
set INCLUDE=C:\PROGRA~1\DASSAU~1\B19\intel_a\.\tools\include\intel_a\1400;C:\PROGRA~1\DASSAU~1\B19\intel_a\.\tools\include\intel_a;C:\PROGRA~1\DASSAU~1\B19\intel_a\.\tools\include;C:\Program Files\Microsoft Visual Studio 8\SDK\v2.0\Include;C:\Program Files\Microsoft Visual Studio 8\VC\include;C:\Program Files\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files\Microsoft Visual Studio 8\VC\PlatformSDK\include
set JLMDeployROOT_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\jlm\jlmdeploy65
set LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Program Files\Microsoft Visual Studio 8\SDK\v2.0\Lib;C:\Program Files\Microsoft Visual Studio 8\VC\lib;C:\Program Files\Microsoft Visual Studio 8\VC\atlmfc\lib;C:\Program Files\Microsoft Visual Studio 8\VC\PlatformSDK\lib
set LOCALAPPDATA=C:\Users\rt\AppData\Local
set LOGONSERVER=\\DESKTOP-101VI2D
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\code\bin
set MkmkADDON_INCLUDE=C:\Program Files\Microsoft Visual Studio 8\SDK\v2.0\Include
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files\Microsoft Visual Studio 8\SDK\v2.0\Lib
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files\Microsoft Visual Studio 8\SDK\v2.0\Bin
set MkmkASPNET20Internal=yes
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=21901
set MkmkDictionary_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\.\code\dictionary
set MkmkIC_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\.\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=C:\PROGRA~1\DASSAU~1\B19
set MkmkMsgCatalog_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\.\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=C:\Program Files\Microsoft Visual Studio 8\VC\include;C:\Program Files\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files\Microsoft Visual Studio 8\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=C:\Program Files\Microsoft Visual Studio 8\VC\lib;C:\Program Files\Microsoft Visual Studio 8\VC\atlmfc\lib;C:\Program Files\Microsoft Visual Studio 8\VC\PlatformSDK\lib
set MkmkMSVCADDON_PATH_80=C:\Program Files\Microsoft Visual Studio 8\VC\bin
set MkmkMSVCDIR=C:\Program Files\Microsoft Visual Studio 8\VC
set MkmkMSVCDIR_80=C:\Program Files\Microsoft Visual Studio 8\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework\v2.0.50727
set MkmkMSVSADDON_PATH_80=C:\Program Files\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files\Microsoft Visual Studio 8\Common7\IDE
set MkmkMSVSBINDIR=C:\Program Files\Microsoft Visual Studio 8\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=32
set MkmkOS_Buildtime=intel_a
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=intel_a
set MkmkReffiles_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\.\reffiles
set MkmkRMSSDK_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\code\bin
set MkmkTOOLSLIB_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a\.\tools\lib\intel_a
set mkmkvers=mkmk Version 2.19.1
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set Mkmk_Modifier=554
set Mkmk_Modifier_BAD=16
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=intel_a
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=C:\PROGRA~1\DASSAU~1\B19\intel_a\code\command\
set NUMBER_OF_PROCESSORS=8
set OneDrive=C:\Users\rt\OneDrive
set OS=Windows_NT
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=C:\Program Files\Microsoft Visual Studio 8\VC\bin;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files\Microsoft Visual Studio 8\SDK\v2.0\Bin;C:\Program Files\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files\Microsoft Visual Studio 8\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\90\Tools\binn\;C:\Users\rt\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Dassault Systemes\B19\intel_a\TCK\command;C:\PROGRA~1\DASSAU~1\B19\intel_a\code\command;C:\PROGRA~1\DASSAU~1\B19\intel_a\code\command;C:\Program Files\Dassault Systemes\B19\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=x86
set PROCESSOR_IDENTIFIER=x86 Family 6 Model 60 Stepping 3, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=3c03
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\rt\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=C:\PROGRA~1\DASSAU~1\B19\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2018/07/03-17:10:00
set TCK_ID=V5R19_B19
set TCK_INSTALL_PATH=C:\Program Files\Dassault Systemes\B19
set TCK_LOCAL_INFO=C:\Program Files
set TCK_NAME=V5R19_B19
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=C:\Program Files\Dassault Systemes\B19\intel_a
set TCK_TMP_FILE=C:\Users\rt\AppData\Local\Temp\tckexec__rt_35863.bat
set TEMP=C:\Users\rt\AppData\Local\Temp
set TMP=C:\Users\rt\AppData\Local\Temp
set TMPFILE=\adl_unset_33967.bat
set USERDOMAIN=DESKTOP-101VI2D
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-101VI2D
set USERNAME=rt
set USERPROFILE=C:\Users\rt
set VBTtmp=C:\Users\rt\AppData\Local\Temp
set VS80COMNTOOLS=C:\Program Files\Microsoft Visual Studio 8\Common7\Tools\
set WecVersionForRosebud.1A7C=2
set windir=C:\Windows
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
