// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATPPRResource.h
// Header definition of CATPPRResource
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2015  Creation: Code generated by the CAA wizard  WANGJIAPENG
//===================================================================
#ifndef CATPPRResource_H
#define CATPPRResource_H

#include "CATPPRDocument.h"
#include "CATDocument.h"

class CATPPRResource: public CATPPRDocument
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATPPRResource ();
     virtual ~CATPPRResource ();

  // Copy constructor and equal operator
  // -----------------------------------
  CATPPRResource (CATPPRResource &);
  CATPPRResource& operator=(CATPPRResource&);

  //获取资源根节点指针
  CATListValCATBaseUnknown_var *GetPPRRootPointer(CATDocument *pProcessDoc);

};

//-----------------------------------------------------------------------

#endif
