// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// CAAETreeNodeNavigModify.h
// Provide implementation to interface
//    CATINavigModify

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CATTreeNodeObj_node
//EXTENSIONTYPE:	DataExtension

//    TIE: CATINavigModify

//End CAA2 Wizard Generation Report
//
//  Feb 2010  Creation: Code generated by the CAA wizard  user
//===================================================================
#ifndef CAAETreeNodeNavigModify_H
#define CAAETreeNodeNavigModify_H

#include "CATNodeExtension.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATINavigModify
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class CAAETreeNodeNavigModify: public CATNodeExtension

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAETreeNodeNavigModify ();
     virtual ~CAAETreeNodeNavigModify ();

    /**
     * Implements a function from an interface.
     * @href CATINavigModify#UpdateElem
     */
     void UpdateElem (CATNavigInstance*  iInst ) ;

    /**
     * Implements a function from an interface.
     * @href CATINavigModify#ModifyShortHelp
     */
     HRESULT ModifyShortHelp (CATUnicodeString&  ioText ) ;

    /**
     * Implements a function from an interface.
     * @href CATINavigModify#Select
     */
     //void Select (int  iMode ) ;

    /**
     * Implements a function from an interface.
     * @href CATINavigModify#IsSelected
     */
     //int IsSelected () ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAETreeNodeNavigModify (CAAETreeNodeNavigModify &);
  CAAETreeNodeNavigModify& operator=(CAAETreeNodeNavigModify&);

};

//-----------------------------------------------------------------------

#endif