// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// CAAECreateInstanceForTreeNode.h
// Provide implementation to interface
//    CATICreateInstance

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CATTreeNodeObj
//EXTENSIONTYPE:	CodeExtension

//    TIE: CATICreateInstance

//End CAA2 Wizard Generation Report
//
//  Feb 2010  Creation: Code generated by the CAA wizard  user
//===================================================================
#ifndef CAAECreateInstanceForTreeNode_H
#define CAAECreateInstanceForTreeNode_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATICreateInstance
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class CAAECreateInstanceForTreeNode: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAECreateInstanceForTreeNode ();
     virtual ~CAAECreateInstanceForTreeNode ();

    /**
     * Implements a function from an interface.
     * @href CATICreateInstance#CreateInstance
     */
     HRESULT __stdcall CreateInstance (void ** oPPV ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAECreateInstanceForTreeNode (CAAECreateInstanceForTreeNode &);
  CAAECreateInstanceForTreeNode& operator=(CAAECreateInstanceForTreeNode&);

};

//-----------------------------------------------------------------------

#endif