// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// CAAETreeNodeSelectStatus.h
// Provide implementation to interface
//    CATITreeNodeSelectStatus

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CATTreeNodeObj
//EXTENSIONTYPE:	DataExtension

//    TIE: CATITreeNodeSelectStatus

//End CAA2 Wizard Generation Report
//
//  Feb 2010  Creation: Code generated by the CAA wizard  user
//===================================================================
#ifndef CAAETreeNodeSelectStatus_H
#define CAAETreeNodeSelectStatus_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATITreeNodeSelectStatus
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class CAAETreeNodeSelectStatus: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAETreeNodeSelectStatus ();
     virtual ~CAAETreeNodeSelectStatus ();

    /**
     * Implements a function from an interface.
     * @href CATITreeNodeSelectStatus#SetSelectStatus
     */
     HRESULT SetSelectStatus (int  iSelectStatus ) ;

    /**
     * Implements a function from an interface.
     * @href CATITreeNodeSelectStatus#GetSelectStatus
     */
     HRESULT GetSelectStatus (int *  poSelectStatus ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAETreeNodeSelectStatus (CAAETreeNodeSelectStatus &);
  CAAETreeNodeSelectStatus& operator=(CAAETreeNodeSelectStatus&);


  int SelectStatus;

};

//-----------------------------------------------------------------------

#endif