// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// CATTreeNodeObj.h
// Header definition of CATTreeNodeObj
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2010  Creation: Code generated by the CAA wizard  user
//===================================================================
#ifndef CATTreeNodeObj_H
#define CATTreeNodeObj_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href CATTreeNodeObj constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new CATTreeNodeObj;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class CATTreeNodeObj: public CATBaseUnknown
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     CATTreeNodeObj ();
     virtual ~CATTreeNodeObj ();


};

//-----------------------------------------------------------------------

#endif