// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// TreeNodeSelectNotif.h
// Header definition of TreeNodeSelectNotif
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2010  Creation: Code generated by the CAA wizard  user
//===================================================================
#ifndef TreeNodeSelectNotif_H
#define TreeNodeSelectNotif_H

#include "ktTreeNodeImplement.h"
#include "CATNotification.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href TreeNodeSelectNotif constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new TreeNodeSelectNotif;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByktTreeNodeImplement TreeNodeSelectNotif: public CATNotification
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     TreeNodeSelectNotif ();
     virtual ~TreeNodeSelectNotif ();

  // Copy constructor and equal operator
  // -----------------------------------
  TreeNodeSelectNotif (TreeNodeSelectNotif &);
  TreeNodeSelectNotif& operator=(TreeNodeSelectNotif&);

};

//-----------------------------------------------------------------------

#endif