// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// CATTreeNodeObj.cpp
// Header definition of CATTreeNodeObj
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2010  Creation: Code generated by the CAA wizard  user
//===================================================================
#include "CATTreeNodeObj.h"
 
CATImplementClass( CATTreeNodeObj,
                   Implementation, 
                   CATBaseUnknown,
                   CATNull );
 
//-----------------------------------------------------------------------------
// CATTreeNodeObj : constructor
//-----------------------------------------------------------------------------
CATTreeNodeObj::CATTreeNodeObj():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// CATTreeNodeObj : destructor
//-----------------------------------------------------------------------------
CATTreeNodeObj::~CATTreeNodeObj()
{
}
 