// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// TreeNodeSelectNotif.cpp
// Header definition of TreeNodeSelectNotif
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2010  Creation: Code generated by the CAA wizard  user
//===================================================================
#include "TreeNodeSelectNotif.h"
 
CATImplementClass( TreeNodeSelectNotif,
                   Implementation, 
                   CATNotification,
                   CATNull );
 
//-----------------------------------------------------------------------------
// TreeNodeSelectNotif : constructor
//-----------------------------------------------------------------------------
TreeNodeSelectNotif::TreeNodeSelectNotif():
    CATNotification()
{
}

//-----------------------------------------------------------------------------
// TreeNodeSelectNotif : destructor
//-----------------------------------------------------------------------------
TreeNodeSelectNotif::~TreeNodeSelectNotif()
{
}
 
//-----------------------------------------------------------------------------
// TreeNodeSelectNotif : copy constructor
//-----------------------------------------------------------------------------
TreeNodeSelectNotif::TreeNodeSelectNotif(TreeNodeSelectNotif& original):
   CATNotification(original)
{
}
 
//-----------------------------------------------------------------------------
// TreeNodeSelectNotif : equal operator
//-----------------------------------------------------------------------------
TreeNodeSelectNotif& TreeNodeSelectNotif::operator=(TreeNodeSelectNotif& original)
{
   CATNotification::operator=(original);
   return *this;
}
 